### ISSUE TITLE
Remove URL prefix from issue keys

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#103]
There have been multiple cases where reporters or commenters include the URL for issue keys or create a link with the issue key as name:
- `https://bugs.mojang.com/browse/MC-123`
- `[MC-123|https://bugs.mojang.com/browse/MC-123]`

This is unnecessary because Jira detects issue keys automatically and adds links and formats them, however not all users know that.
Having these as link instead of issue key is irritating because they
- don't have hover text
- aren't strike through when the issue is resolved

Maybe it would be worth having Arisa change the links?

Security considerations: In case Arisa checks if the referenced issue exists before removing the URL prefix, then it must not consider private issues, otherwise this would allow non-staff users querying which private issues exist by checking whether Arisa removes the URL prefix.

**Comment by violine1101** [comment]
What should it do if the display title and link don't point to the same ticket? I've seen this quite a few times. This should be a case that is to be kept in mind.

Should Arisa only edit incoming comments or older comments as well?

Also, links like `https://bugs.mojang.com/projects/MC/issues/MC-123` should probably also be replaced as well, those are especially annoying (although they only occur very rarely).

**Comment by urielsalis** [comment]
I would say that if it detects https://bugs.mojang.com/browse/XXXXXX, https://bugs.mojang.com/projects/XXXX/issues/XXXXXXXX or [anything|https://bugs.mojang.com/browse/XXXXXXX] it should just delete it and replace it with XXXXXX. No checking if it exists, its private or anything, just replace

**Comment by NeunEinser** [comment]
I don't see why a user would link to an url that is obviously meant to be a ticket URL. I think it's safe to just always remove the URL part, without exist checks.

**Comment by violine1101** [comment]
> `[anything|https://bugs.mojang.com/browse/XXXXXXX]`

This might cause issues in case someone used this intentionally, for example:

```
[A similar issue with XYZ was fixed previously|https://bugs.mojang.com/browse/XXXXXXX], so I expect that this is a valid bug too.
```

**Comment by urielsalis** [comment]
[XXXXXXX|https://bugs.mojang.com/browse/XXXXXXX]

then :P
