### ISSUE TITLE
Automatically apply votes from duplicate to master if user has not already voted for it.

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NeunEinser** [comment]
I don't think this is possible, at least not with arisa, as we cannot vote in the behalf of a user, and Arisa essentially has the same permissions as a moderator.
Quickly looking at the API, it does not seem like this is supported at all: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-issue-issueIdOrKey-votes-post

**Comment by MikeUnverferth** [comment]
OK, withdrawing request.
