### ISSUE TITLE
Add "duplicates" comment when it does not exist

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#116]
There exists a helper message template for when a report is a duplicate, see https://mojira.github.io/helper-messages/:
> ...
We're actually already tracking this issue in **MC-123**, so I've resolved and linked this ticket as a duplicate.
...

However, adding that manually is tedious.
Maybe it would be good if Arisa automatically added it, either always or if the reporter is new (e.g. only has a few reports) so they learn about the search feature. Arisa would have to choose the correct template based on the project then because some links such as the "Issue Guidelines" link are project specific. And it should not add a comment if one already exists. This might be a little bit tricky because sometimes non-staff members add such a comment.

If this functionality was added, all staff members would have to be informed to prevent them adding a duplicate comment by accident when Arisa already added one.

Maybe this effort is not worth it though, what do you think?

**Comment by SPGoding** [comment]
I guess it would be possible to check whether the parent ticket ID has been mentioned before in the comments

**Comment by urielsalis** [comment]
As another idea, we could tell the mods to not add the message themselves and let arisa handle it with the proper helper message?

**Comment by Pokechu22** [comment]
The duplicate message isn't always the same as the one in the help messages, as it can be useful to elaborate on why it's a duplicate (e.g. covered as a single aspect of another issue, or it's a detail in the steps to reproduce).  Even within the helper messages, there are the tech support, wai, private, etc messages.

I think checking for the parent ID in the comments would be fine (perhaps it could cause issues for duplicates of multiple issues, though).  Alternatively, we could check if *any* comment was left when resolving.

**Comment by NeunEinser** [comment]
It would also be nice if the module would check the parent for its resolution, so the correct message can be used.

Otherwise, I agree. For example for the heightmap issues, I used the "Duplicate (fixed)" as a preset and modified it to say to look at the parent for fixing it in worlds that were opened in the faulty snapshot.

**Comment by Marcono1234** [comment]
Maybe similar to the other modules wait some time (e.g. 5 minutes) so the mod can add the comment themselves before Arisa adds it?

----

> Alternatively, we could check if _any_ comment was left when resolving.

That might work. The use case I was thinking of was when a new version was released and dozens of duplicates were created. In these cases there were no comments.
