### ISSUE TITLE
"Awaiting Response" reports are reopened on update by staff member

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#117]
It appears "Awaiting Response" reports are reopened when updates are performed by staff members. This is most likely undesired. For example I resolved a report as "Awaiting Response", then marked another report as duplicate of that (the reporter created the same report twice) and the report was reopened.

One tricky situation might be where the reporter (or another user) performs an action, then in the meantime a staff member performs an action (without seeing the user action yet) and then Arisa notices the update. In that case it would see the staff member update as last action even though a user action happened before and the report should be reopened.

**Comment by violine1101** [comment]
See also #56
