### ISSUE TITLE
Port security module

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#12]
https://github.com/mojira/arisa-js/blob/master/checks/ModuleSecurity.js

**Comment by NeunEinser** [comment]
I am unsure of how to do this or how it was ever possible.
The module seems to be there to change the security level to public, when it is undefined:
https://github.com/mojira/arisa-js/blob/master/checks/ModuleSecurity.js#L25

I quickly checked and there does not seem to be any project that has a security level for "public", it's always unset or private.

Furthermore, the jira endpoint `GET /rest/api/2/project/{projectIdOrKey}` does not return information about security levels.

The endpoint `GET https://bugs.mojang.com/rest/api/2/project/{project-key}/issuesecuritylevelscheme` seems to be pretty the closest to what we'd need, however even with a MOD account you get `403 Forbidden`
```json
{
    "errorMessages": [
        "You need to be a Jira administrator to perform this operation"
    ],
    "errors": {}
}
```

According to the (Jira API documentation)[https://developer.atlassian.com/cloud/jira/platform/rest/v2/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-rest-api-2-project-projectKeyOrId-issuesecuritylevelscheme-get] it returns something like this if you can access it:
```json
{
  "self": "https://your-domain.atlassian.net/rest/api/2/issuesecurityschemes/10000",
  "id": 10000,
  "name": "Default Issue Security Scheme",
  "description": "Description for the default issue security scheme",
  "defaultSecurityLevelId": 10021,
  "levels": [
    {
      "self": "https://your-domain.atlassian.net/rest/api/2/securitylevel/10021",
      "id": "10021",
      "description": "Only the reporter and internal staff can see this issue.",
      "name": "Reporter Only"
    }
  ]
}
```

This however does not include any mapping with a key of `public`, as present in the js version (`issue.project.security.public`)

Using the `GET /rest/api/2/issue/{issueIdOrKey}/editmeta` endpoint, with a valid issue ID, the security level is described as follows:
```json
"security": {
    "required": false,
    "schema": {
        "type": "securitylevel",
        "system": "security"
    },
    "name": "Security Level",
    "operations": [
        "set"
    ],
    "allowedValues": [
        {
            "self": "https://bugs.mojang.com/rest/api/2/securitylevel/10318",
            "id": "10318",
            "description": "Private, viewable only by volunteers and up.",
            "name": "Minecraft - Private"
        }
    ]
}
```

**Comment by urielsalis** [comment]
I dont think this has triggered in a while. Im closing the issue
