### ISSUE TITLE
Language test did not identify Italian

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#120]
https://bugs.mojang.com/browse/MCPE-70192 was identified as not English but did not show that it was Italian (per google translate anyway).

**Comment by NeunEinser** [comment]
Relevant for this as well:
Summary `No me anda el minecraft`
Description `no me anda minecraft`
(This was done on a testing ticket to which not everyone has access to)

Was detected as either Spanish or Italian (it is Spanish), both with a confidence of 50% each.

**Comment by NeunEinser** [comment]
Oh, interesting.

For the one you posted, we actually get it with a confidence of 100%.
The config just doesn't have a message for Italian.

**Comment by violine1101** [comment]
Yes, I only added a limited selection of languages to the config since the previous version of the module using lingua used enormous amounts of RAM if you didn't limit which languages it was able to detect. This is no longer the case with the current version.

**Comment by NeunEinser** [comment]
Should we just add more languages in general then?
In the end it's just a matter of how many translations we can get, I guess.

**Comment by urielsalis** [comment]
Our API supports 40 languages, we could add all or most of them and just use en 2 code letter if not found
