### ISSUE TITLE
Mark as community consensus if linked > 0 and unconfirmed

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#123]
**What is the problem the module is aiming to solve? Please describe.**
Mark as community consensus if linked > 0 and unconfirmed

**Comment by NeunEinser** [comment]
It probably should still set to cc, when it's set to plausible

**Comment by Marcono1234** [comment]
We would have to clarify for all moderators though, that if a person duplicates their own report, we must not resolve that as duplicate (or prevent Arisa from picking up these cases).
Otherwise people are able to "confirm" their own reports.
