### ISSUE TITLE
Change the CSS color of Arisa

### ISSUE THREAD

**Issue by Oval** [mojira/arisa-kt#132]
More cosmetic, not really technical. But I would suggest to ask Adrian to change the color of Arisa to light-ish gray. Would help a lot with people who sometimes think this isn't a bot due to having the same color as moderators. - I'm sure this is possible as it's just a color code and it's set individually for every volunteer anyways. **EDIT:** Just like Piston bot has a red color (presumably because it has the 'staff' perms) maybe it should change it color to light-ish gray too?

**Comment by NeunEinser** [comment]
This has been forwarded to an internal tracker for Mojang.
Since this is not something we can do in this repo, I am going to close this now.
