### ISSUE TITLE
arisa-kt crashing

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#133]
07:47:46.327 [main] INFO  Arisa - Connected to jira
Apr 21, 2020 7:47:57 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request: The target server failed to respond
Apr 21, 2020 7:47:57 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request

**Comment by NeunEinser** [comment]
I haven't seen this message in the logs since a while.
Do you know when this can happen / if it's still an issue?

**Comment by urielsalis** [comment]
Doesnt seem to be happening, but might if mojira goes down again. Do we retry connecting to Mojira?

**Comment by NeunEinser** [comment]
#113 is still open

**Comment by urielsalis** [comment]
Lets merge both into #113 then
