### ISSUE TITLE
Add a Github Action that validates arisa.json

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#148]
## The Problem
It is possible to merge an invalid json, since `arisa.json` is not validated

## Possible Solution
A Github action that validates `arisa.json` should be added.
Similarily to mojira/helper-messages#34, a json schema should be added.

It might make sense to look into #100 first and change this issue accordingly.

**Comment by urielsalis** [comment]
@SPGoding got any ideas on how we can do this? Schema like in helper-messages or actually starting the app?

**Comment by SPGoding** [comment]
Imho it might be painful to maintain such a schema since we will keep adding new settings. If we can manage to generate a schema from `ConfigSpec` then that won't be a big problem though.

**Comment by urielsalis** [comment]
the other option is a test that starts the bot and sees if it can read the configuration correctly, which shouldnt be too hard
