### ISSUE TITLE
Add a command for adding archived versions to affected or fix versions

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#157]
## The Problem
In some rare circumstances, it might be desirable to add an archived version to either the affected or the fix versions. This cannot be done via JIRA natively and needs to be done via the API.

## Possible Solution
When Arisa receives a comment with the contents `!fixed <version>` (where `<version>` is any version available on JIRA), it will add the respective version to the "Fix version/s" list (and resolve the ticket as fixed if it isn't already). Similarily, when it receives a comment containing `!affects <version>` it will add the version to the list of affected versions.

Since this action is irreversible, the command should only be able to moderators, and maybe helpers as well. Commands by other users should be ignored.

It might be a good idea to restrict the comment as soon as it is processed (if it isn't restricted already), so that normal users don't spam the comments with those commands.

Of course the commands could also look differently, this is just my suggestion.

**Comment by Marcono1234** [comment]
Re #158: Maybe (?) use a command format which is consistent for both actions and indicates that this is related to Arisa, so we later know the meaning of the comment.

**Comment by violine1101** [comment]
Would you have any suggestions? I'm not really sure about the command format I proposed myself, but the syntax should probably not be more complicated than it needs to be.

**Comment by NeunEinser** [comment]
If #158 is supposed to have the same format, we need to have a tag format that can be detected and removed, as in RemoveNonStaffMeqs.
Otherwise we face the problem of regular users being able to use those tags and no good way of telling whether it's a former volunteer or someone who posted it and got hidden by a moderator.

**Comment by NeunEinser** [comment]
If #158 is supposed to have the same format, we need to have a tag format that can be detected and removed, as in RemoveNonStaffMeqs.
Otherwise we face the problem of regular users being able to use those tags and no good way of telling whether it's a former volunteer or someone who posted it and got hidden by a moderator.

**Comment by violine1101** [comment]
It should probably only act on incoming comments, there's not really a point of checking older comments as this would be a new thing. Comments like this that don't come from team members should probably just be ignored.

**Comment by NeunEinser** [comment]
There is no way to distinguish between a comment from a former volunteer and the comment from an actual volunteer.
While it would obviously be an option to ignore older comments for adding archived versions, this does not work for #158, and Marcono proposed that both #158 and this should be consistent.

**Comment by violine1101** [comment]
Ah. I don't think they need to be consistent, this one is about a single action that needs to be taken by the bot (i.e. a command) that doesn't need to be acted upon more than once, while #158 is more about a flag that will prevent the ticket from being reopened until it is removed (so it might be more than one action).

Plus, this is a new module, #158 is an extension to an existing module (the ReopenAwaiting one).

I understood Marcono's comment more as proposing to keep the syntax consistent. For instance if we have the keyword for #158 being `ARISA_KEEP_AR` we could use the commands `ARISA_ADD_VERSION 12w34a` and `ARISA_FIXED 12w34a` for this.

**Comment by NeunEinser** [comment]
> I understood Marcono's comment more as proposing to keep the syntax consistent. For instance if we have the keyword for #158 being `ARISA_KEEP_AR` we could use the commands `ARISA_ADD_VERSION 12w34a` and `ARISA_FIXED 12w34a` for this.

Yes, that is exactly my point.
If the syntax IS consistent, we need a syntax that uses some form of detectable tag, so that we can hide and break comments using this tag, as it is done in RemoveNonStaffMeqs.

ARISA_ as prefix for that would be consistent.

**Comment by urielsalis** [comment]
Split into #277 and #278
