### ISSUE TITLE
Arisa breaks valid links

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#159]
## The Bug
Arisa can break valid links to the bug tracker, if the URL contains parameters.

## Example Ticket
Example: https://bugs.mojang.com/browse/MCPE-47294
Arisa replaced `https://bugs.mojang.com/browse/MCPE-38374?focusedCommentId=555054&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-555054` with `MCPE-38374.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-555054 `

## Expected behavior
Arisa should only replace the link for URLs without any parameters.

**Comment by NeunEinser** [comment]
I disabled the module until this is fixed.

**Comment by SPGoding** [comment]
Oops, sorry. I didn't think about the query parameters for locating comments. My fault!
