### ISSUE TITLE
TransferVersionModule adds new affected versions to closed tickets

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#166]
## The Bug
The TransferVersionModule also adds new affected versions to tickets that have already been closed (as WAI or Invalid for instance). We usually tell users that they shouldn't bother adding new affected versions to already closed tickets because it only clutters up the activityfeed.

Additionally, often we have some straggelers that stick on an older update (snapshot) for a while and experience an already fixed bug but need to select a newer version in their ticket. If such a ticket is resolved as a duplicate (which is what we usually do), Arisa would add the newer version that isn't actually affected to the parent ticket as well, which would cause confusion (and frustration if the mod then needs to go to the parent ticket and remove the version again).

## Example Ticket
https://bugs.mojang.com/browse/MC-173366

## Expected behavior
Arisa should not add new affected versions to a ticket if it has been resolved.

**Comment by NeunEinser** [comment]
Should versions be added to AR or CR?

**Comment by violine1101** [comment]
I imagine in these cases that would most likely be handled by the human moderator anyway, so I don't think it's necessary to make an exception for AR and CR.

For AR, it also reopens the ticket anyway when a ticket is resolved as a duplicate of it.

**Comment by NeunEinser** [comment]
> 
> 
> I imagine in these cases that would most likely be handled by the human moderator anyway, so I don't think it's necessary to make an exception for AR and CR.
> 
> For AR, it also reopens the ticket anyway when a ticket is resolved as a duplicate of it.

Are you sure?
From what I saw in the code, it should only reopen in case of an added comment.
