### ISSUE TITLE
RevokeFieldChangesModule: Ignore old Mojang Priority "Normal" changelog entries

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#182]
## The Bug
Originally, all tickets had Mojang Priority set as Normal. However, that was changed when the workflow was changed from "Global Mojang Workflow" to "Java Workflow", as the default value for the Mojang Priority field was now EMPTY. There was no changelog entry for this change (see https://bugs.mojang.com/browse/MC-123693 for example).

Arisa incorrectly resets the priority to "Normal" on tickets where this happened.

## Example Ticket
https://bugs.mojang.com/browse/MC-11739

## Expected behavior
Arisa should ignore all changelog entries that set "Mojang Priority" to Normal if they were before June 5.

**Comment by urielsalis** [comment]
I dont think the module exists anymore. Is this still an issue?

**Comment by NeunEinser** [comment]
It is something we still must consider in #195.
The temporary removal of a module is not an acceptable resolution for an issue, but if you want you can add it in a comment in that pr for reference instead.

**Comment by chandler05** [comment]
I'm going to close this as #195 was closed, and because users can no longer update the Mojang Priority, so this is no longer an issue
