### ISSUE TITLE
Arisa incorrectly removes MEQS even if the ticket has not been triaged

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#184]
## The Bug
Arisa removes MEQS with the reason that the ticket has been triaged (which it has not).

## Example Ticket
https://bugs.mojang.com/browse/MCL-13912
https://bugs.mojang.com/browse/MC-179352

## Expected behavior
Don't remove MEQS because the ticket has been triaged if the ticket has not been triaged

**Comment by NeunEinser** [comment]
Only tickets that were updated recently seem affected, though the module wasn't touched since forever -- what changed?

**Comment by NeunEinser** [comment]
Closed in #194

**Comment by violine1101** [comment]
Was not fixed, still happens https://bugs.mojang.com/browse/MC-182400

**Comment by NeunEinser** [comment]
An old screen was running (see #197), should be fixed in the version now.
Please reopen if you see it happening again *now*

**Comment by violine1101** [comment]
Yes, has been fixed for good now! Tested on https://bugs.mojang.com/browse/MC-182449
