### ISSUE TITLE
Crash module is malfunctioning and spams comments without resolving the ticket

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#189]
## The Bug
For some reason (???) Arisa just spams comments without resolving the ticket when it discovers a ticket is invalid

## Example Ticket
https://bugs.mojang.com/browse/MC-182391

## Expected behavior
Don't do that

**Comment by urielsalis** [comment]
resolve should be before adding comments

**Comment by violine1101** [comment]
ideally it should do both together in the same request to the api, if that's possible (should be)

**Comment by NeunEinser** [comment]
Closed in #194
