### ISSUE TITLE
Prevent Arisa from spamming a ticket

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#190]
## The Problem
In order to avoid things like #189 from happening again, there should probably be a check somewhere that prevents Arisa from doing the same action on the same ticket multiple times in a row.

## Possible Solution
Keep track of when Arisa does an action on a ticket in a database (or similar), and if there is a recent entry for an action that is about to be done, don't do it (and log a warning, because it indicates a malfunctioning module).

Alternatively Arisa could ignore ticket updates where the last changelog entry is from itself, but that could cause other issues, for example since multiple modules may apply to the same ticket.

**Comment by urielsalis** [comment]
I would implement it as: If the most recent action is a comment from arisa, prevent adding further comments

**Comment by NeunEinser** [comment]
There are cases where we might want 2 different comments underneath of each other.
E.g. attachment module removes an attachment, and then gets resolved by some of the other modules, or there is an old comment, no comment after that (but some other update) and then it wants to post a message again.

I think it would be better to check the text of its last comment and check if it's the same as the text it wants to add.

**Comment by urielsalis** [comment]
that check might fail if you add 2 comments as the first one is not going to be the last comment

**Comment by NeunEinser** [comment]
Sure, if you want to catch multiple modules spamming at the same time, you need to actually cache the actions from last run and see if there is something similar, like violine suggested. But that's more complicated.
