### ISSUE TITLE
Arisa adds a single changelog entry per action

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#192]
## The Problem
Arisa adds a single changelog entry for every single action that it takes. That can get quite spammy at times.

This affects every module that does more than one action as far as I can tell.

## Example ticket
https://bugs.mojang.com/browse/MC-159283

## Possible Solution
Group API requests. This is possible because we as moderators can do that via the website. This is probably not easy to implement.

**Comment by NeunEinser** [comment]
It is possible using the current API, I would prefer doing #84 together or before this, as both require a substantial rewrite of Jira.kt

**Comment by SPGoding** [comment]
Note: not all requests can be grouped to a single ChangeLogItem. Here's an real life example made by a human moderator at [MC-184274](https://bugs.mojang.com/browse/MC-184274):
![image](https://user-images.githubusercontent.com/15277496/82389716-7c0c1480-9a02-11ea-8f41-bd17957d9c82.png)

What we will be able to do is to group field changes (e.g. adding affected versions) that are happened in the same run together.

**Comment by urielsalis** [comment]
We can also group comments with resolves
