### ISSUE TITLE
Arisa sometimes starts twice

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#197]
## The Bug
This seems like a deployment error. Most noticeable by the fact that the LanguageModule left two comments instead of one, until my most recent commit to `master`. Also happens with other actions, such as UpdateLinked as well.

## Example Tickets
Double LanguageModule comment:
* https://bugs.mojang.com/browse/MCPE-75474
* https://bugs.mojang.com/browse/MCPE-75476
* https://bugs.mojang.com/browse/MCPE-75485
* https://bugs.mojang.com/browse/WEB-2269

Double UpdateLinkedModule update:
* https://bugs.mojang.com/browse/MCPE-74369

## Expected behavior
Only start once.

**Comment by NeunEinser** [comment]
Not fixed
