### ISSUE TITLE
Automatically make "master" ticket summaries bold.

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#217]
## The Problem
For commonly-duplicated bugs, it can be hard to find the master when searching, especially for general users who may not know about showing/sorting on other fields like votes/links.

## Possible Solution
If a ticket has more than a certain threshold of duplicates (3 or so maybe), adjust the summary using markdown/markup to have it show as bold in the list. Also, for projects such as REALMS that don't have a Links field it should still be able to adjust based on the link count.

**Comment by NeunEinser** [comment]
What do you mean?
The actual summary field, as in what shows up when searching for issues?
![image](https://user-images.githubusercontent.com/12124394/81181927-6bdd4980-8fad-11ea-9ba1-3cb5aa1b0739.png)

How would you make that bold?

**Comment by violine1101** [comment]
It's not possible to format the summary as far as I know.

**Comment by MikeUnverferth** [comment]
I did see some a week or so ago that had formatted summaries somehow, but I didn't look at the time to see how it was done. Maybe it was just a transient issue and it really isn't possible to do the formatting.
