### ISSUE TITLE
ReopenAwaiting seems broken

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#218]
## The Bug
Since the merge of #199, it seems like Arisa never reopened issues from ReopenAwaiting again, despite it being needed

## Example Ticket
[MCPE-75860](https://bugs.mojang.com/browse/MCPE-75860)
[MCPE-62139](https://bugs.mojang.com/browse/MCPE-62139)
[MC-182693](https://bugs.mojang.com/browse/MC-182693)
[MC-182588](https://bugs.mojang.com/browse/MC-182588)

## Expected behavior
It should have reopened that ticket after the comment.

**Comment by urielsalis** [comment]
Fixed with #220
