### ISSUE TITLE
Set tickets back to unconfirmed if it wasnt done by Mojang, Mod or Helper

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#22]

**Comment by urielsalis** [comment]
This was fixed already, should we keep it?

**Comment by Pokechu22** [comment]
I think it'd be useful to have this in case the behavior regresses.

**Comment by urielsalis** [comment]
Should we check the display name of the user?

I seen Mod, Mojang, MCPE Mod, Minecraft in use. Any others?

**Comment by NeunEinser** [comment]
You should be able to check permission groups of a user directly, will look into it tomorrow.
