### ISSUE TITLE
Language module test - False detection (German, MC-182790)

### ISSUE THREAD

**Issue by Whomsky** [mojira/arisa-kt#225]
Arisa detected that the ticket is in German, however it doesn't seem to contain anything thats actually German.

https://bugs.mojang.com/projects/MC/issues/MC-182790

I dont see why it detected the report as German, but it's definitely english

**Comment by violine1101** [comment]
Another false positive https://bugs.mojang.com/browse/MC-182947

**Comment by violine1101** [comment]
Should we merge this into #142?
