### ISSUE TITLE
Set issues containing an email address to private 

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#227]
## The Problem
It happens frequently that account issues are submitted containing an email adress but the reporter doesn't set it to private. Arisa could set those automatically to ptivate.
It shouldn't leave a keep private comment though, so it still pops up in filters and human mods can take a look at it and set it to public again, when aplicable.

I am also thinking of the Language module which currently sends all data to a third party server, if they are not private. When this is implemented, emails would also not be sent to them

## Possible Implementation
A regex should check the summary, enviornment and issue text and search for any valid email adresses.
The module should only work on issues that have been created since the last run (in case a moderator purposefully set it to public, Arisa should not set it to private again).

If applicable it should then set the security level to private, similarily as the keep private module does.

**Comment by Marcono1234** [comment]
> I am also thinking of the Language module which currently sends all data to a third party server, if they are not private. When this is implemented, emails would also not be sent to them

Would this really work? I am not familiar enough with Arisa, but would the language module see when this module set the report to private in the same run (assuming order of module execution is already correct)?
