### ISSUE TITLE
Remove review tag on reviewed issues

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#24]
Review tags should be removed automatically when the issue is either reopened or receives a reviewed tag by Mojang.

This requires some changes to how Arisa selects issues to take a look at though, as it currently requires the latest action on the ticket not being a transition:
https://github.com/mojira/arisa-kt/blob/71780cfe533c8132b78ca8e0c969c10053e140db/src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt#L105-L108.

This is probably done to prevent arisa from transitioning an issue again, after a mod revoked something Arisa did.

Because of this, it is currently impossible to do an automatic action on a ticket that was reopened as the last action.

**Comment by violine1101** [comment]
In my opinion, Arisa shouldn't remove the comment with the tag, but instead just edit the comment to invalidate the review tag, so that potential comments apart from the tag itself are kept.

**Comment by NeunEinser** [comment]
That's what I meant by removal.
There are places where arisa-kt already removes tags by removing the "MEQS" from it.

Besides that, Arisa has the same permissions as a moderator and thus cannot delete comments anyways, only change visibility or otherwise edit them.

**Comment by urielsalis** [comment]
Can we instead edit it for a MEQS_REVIEWED_ARISA?

**Comment by NeunEinser** [comment]
If you want to keep track of tags removed by arisa, it might be a good idea to just always add something like MEQS_ARISA_REMOVED, when a tag is removed by any module.

**Comment by NeunEinser** [comment]
Maybe even MEQS_ARISA_REMOVED_<tag>
Something like `MEQS_REVIEWED_ARISA` might break some filters.

**Comment by urielsalis** [comment]
MEQS_ARISA_REMOVED_<TAG> sounds good

**Comment by urielsalis** [comment]
Now that we use MEQS_ARISA_REMOVED, can we just add this tag to the list of the ones automatically edited?

**Comment by NeunEinser** [comment]
Which list?

**Comment by urielsalis** [comment]
https://github.com/mojira/arisa-kt/blob/master/src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt#L82

**Comment by NeunEinser** [comment]
Ah the one from the reviewed module ^^
That would partly work I guess for "remove tag when reviewed" part, so sure ^^

There is still the issue that https://github.com/mojira/arisa-kt/blob/master/src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt#L127-L136 currently prevents modules from running when the last action was a reopen, but if they change the Mojang priority after that, or the issue simply gets updated after that, that should already work.

Removing the tag when Mojang adds `MEQS_REVIEWED` on the other hand would probably need a new module though.

**Comment by NeunEinser** [comment]
Oh, also for `MEQS_REVIEWED`, the bot doesn't run on resolved tickets at all, so that's kind of hard anyway.

But yeah for removing the tag after they reviewed + triaged the issue, sure that would already partly resolve this, the other part would require a refactor similar to what was suggested in #38, possibly adding the option to disable that check per module.

**Comment by violine1101** [comment]
IMO this is no longer needed due to the processes that are currently in place.

**Comment by NeunEinser** [comment]
I agree.
I don't think there is much value in the RemoveTriagedMeqs module either, as we could just alter the WAI filters to check for untriaged reports.

**Comment by violine1101** [comment]
> I don't think there is much value in the RemoveTriagedMeqs module either, as we could just alter the WAI filters to check for untriaged reports, but that's a different story.

Agreed, I've created a new ticket for that → #384

I've closed this ticket now.
