### ISSUE TITLE
Use named parameters for Jira Domain

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#242]
Use named parameters for Jira Domain with defaults to avoid having to change all tests/modules when adding a new one

**Comment by SPGoding** [comment]
In production, these Domain classes are only used to construct objects in `Mappers.kt` iirc, so there's no need to add defaults to the constructors as there won't be much changes if we modify them. I suppose keeping functions like this in each test should be sufficient and we can set different default values for different module tests:

https://github.com/mojira/arisa-kt/blob/a422665638eb1599d0e813bc4f22daa73586a4b1/src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt#L575-L593
