### ISSUE TITLE
[META] Add autolinked references to this repository

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#245]
See https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls

Not a big deal ;D

**Comment by NeunEinser** [comment]
Wdym? `#245` converts to the link #245 by typing it. That's just a help page how github deals with this, you don't have to add anything.

**Comment by urielsalis** [comment]
I think he means https://help.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources, where we would be able to autolink jira tickets. But thats not available without paying

**Comment by SPGoding** [comment]
Oh really? I thought that was a free service for public organizatioms
