### ISSUE TITLE
Hide comments that sound official

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#262]
## The Problem
Some users may use the helper messages in their comments and cause confusion.
## Possible Solution
Also check the body of the comment in `HideImpostorsModule`. We need to have a clear criteria to tell if a comment sounds official. My proposal would be to try match the full Quick Links part, or the `(Thank you|Thanks) for (the|your) report` part?

**Comment by violine1101** [comment]
I personally don't think this is a feature that the bot should have. Things like this are rare enough that we can handle it manually. If this feature was implemented it would probably cause more issues than it solves.
