### ISSUE TITLE
Resolve empty tickets as AR instead of Incomplete

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#263]
## The Problem
Some users might complete their ticket after it's resolved as Incomplete (e.g. [MC-184810](https://bugs.mojang.com/browse/MC-184810)), which might be ignored by us.
## Possible Solution
Resolve these tickets as Awaiting Response instead.

What's your opinion?

**Comment by urielsalis** [comment]
I think I remember us discussing this.  This is one of the arisa-js modules after all

We have to look into how often they are filled after the fact, I remember that being too low and it would stay in AR forever

**Comment by SPGoding** [comment]
Another option I can come up with would be to clearly specify that the reporter have to create a new issue in the comment

**Comment by Marcono1234** [comment]
It happens now and then that people add the relevant information, but there are also a lot of unuseful and spam reports. JQL query:
```
project != MCTEST and comment ~ "bot incomplete" order by createdDate
```

**Comment by NeunEinser** [comment]
I think it would be better to alter the message.
