### ISSUE TITLE
Arisa incorrectly closes tickets as incomplete

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#271]
## The Bug
Arisa closed this ticket as incomplete: https://bugs.mojang.com/browse/WEB-2408

## Example Ticket
https://bugs.mojang.com/browse/WEB-2408

## Expected behavior
Don't do that

**Comment by violine1101** [comment]
Whoops, just noticed the reporter edited their ticket afterwards.

But perhaps Arisa should check for that sort of stuff and reopen the ticket if more information is added?

**Comment by urielsalis** [comment]
Thats #263
