### ISSUE TITLE
Create CLA for external contributors

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#275]
Use something like https://github.com/cla-assistant/github-action to ask non-mojira contributors to sign an CLA

We can use the Microsoft one as a base

Things we should include:
the contributor is the author of the contribution;
the contributor has the legal right to grant the copyright license;
the contributor does not have an employer that can claim rights in the copyright;
the contributor is giving us right to use his work in the project and relicense it if needed;
the contribution is an original work;
the contribution is not subject to third-party licenses, claims, suits, or actions.

**Comment by urielsalis** [comment]
@SPGoding @NeunEinser opinions?

**Comment by SPGoding** [comment]
I know nothing about legal documents, so no opinions lol. Anyways the list you gave looks good to me.
