### ISSUE TITLE
Transfer Mojang Priority to parent tickets

### ISSUE THREAD

**Issue by miwob** [mojira/arisa-kt#276]
## The Problem
Currently, when resolving duplicates that have a _Mojang Priority_ set, it leaves the parent ticket with no priority if there's none assigned. The same applies to _Triaged Time_ from what I can see.

## Possible Solution
Simply transfer the aforementioned fields to the parent ticket. Highest priority should be kept in case the parent ticket already has a priority set. Whether the original _Triaged Time_ can be easily transferred is unclear to me.

**Comment by Marcono1234** [comment]
> Highest priority should be kept in case the parent ticket already has a priority set.

This might not always be desired, e.g. when the lower priority is the "correct" one. Though I am not sure how such a situation can be solved.

**Comment by urielsalis** [comment]
Can we ask if they are okay with this?

**Comment by urielsalis** [comment]
Closing after discussion with Mojang
