### ISSUE TITLE
Add command for adding affected versions

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#277]
## The Problem
Split from #157

## Possible Solution

Add a command, triggered by a volunteer adding a staff comment with "ARISA_ADD_VERSION 12w34a"

**Comment by NeunEinser** [comment]
(Or a helper comment, as affected versions are accessible by Helpers anyways and they could do the same through the API)

**Comment by Marcono1234** [comment]
What should happen when the specified version does not exist (e.g. because it was mistyped). Should Arisa silently ignore it or should it add a helper-restricted comment?

**Comment by urielsalis** [comment]
In the current implementation im doing it would return a FailedModule error and log to console. Left a todo for editing a ticket with the result of a command (which probably will end up being a separate issue)
