### ISSUE TITLE
Add command for adding fixed versions

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#278]
## The Problem
Split from #157

## Possible Solution

Add a command, triggered by a volunteer adding a staff comment with "ARISA_FIXED 12w34a"

Discussion: should this be allowed for helpers?

**Comment by NeunEinser** [comment]
Helpers currently cannot add fixed versions, so they shouldn't be able to.

**Comment by urielsalis** [comment]
I know that they cant because they cant resolve tickets, but im intending this module to both close the issue as fixed and add the version, so it might be interesting to add Mojang if they want this to be allowed for helpers

**Comment by Marcono1234** [comment]
#279 added `FixedCommand.kt`, however it has no functionality yet.

**Comment by urielsalis** [comment]
Yep. left it as a note in the code and in the PR :)

**Comment by urielsalis** [comment]
Should be left as mod only
