### ISSUE TITLE
Arisa doesn't expect helper message variables to contain other variables

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#282]
## The Problem
If a helper message variable contains another variable, Arisa might not resolve it correctly. This is currently not an issue yet, but the proposed change in https://github.com/mojira/helper-messages/pull/62 would break Arisa. If that PR is merged without Arisa being adjusted, this would turn into a bug.

## Expected behavior
Arisa should be able to resolve all variables inside of variables up to a certain point, so that variables can include other variables, but only up to a certain limit (so that Arisa doesn't get stuck in an infinite loop). Here's an example of how I did it in JavaScript: https://github.com/mojira/helper-messages/pull/62/commits/0c44006f8589eaf3b872b471b2607ca6136b581e#diff-36f8d737c0d72482b317e9b95c615dc2

**Comment by urielsalis** [comment]
ideally you add the ones you are using into the test, and the test checks that they exist :/
