### ISSUE TITLE
Document checks, modules and commands in Wiki/Readme

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#286]
Document checks, modules and commands in Wiki/Readme

**Comment by Marcono1234** [comment]
The issue with GitHub wikis is that there is no direct relation to the actual repository (if I understand it correctly). So you perform a change in the main repository and then separately have to edit the wiki. Additionally (while writing this) you cannot create pull requests for wikis.

I would therefore suggest to add a `docs` folder and create markdown documents there. This then allows to create commits which add features and at the same time add the necessary documentation.

**Comment by urielsalis** [comment]
Done via wiki, commands done, needs to be done for modules

**Comment by Pokechu22** [comment]
The wiki is technically a separate git repository (clone as https://github.com/mojira/arisa-kt.wiki.git) but you can't submit pull requests to it.  I don't really have a preference between a `docs` folder and using the wiki though.
