### ISSUE TITLE
Add a delay to keep AR comments

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#301]
## The Problem
When a ticket is kept in AR, Arisa should not reply to every single comment if there are many comments in a short amount of time.

Relates to, but is not the same as #190.

## Example Ticket
https://bugs.mojang.com/browse/MC-187083

## Possible Solution
Check if there have been any comments by arisa on a ticket recently (in the past day or so) and if there are, don't leave a comment. I don't know whether there's a feasible way to check whether the recently added comment(s) is the "no-reopen-ar" comment or not.

**Comment by Odysseius** [comment]
I would prefer to scrap the AR comments entirely. In my opinion, it is up to the person who put the KEEP_AR to monitor the ticket and all answers coming from the user - at the moment, after each and every comment - no matter the content - the message gets posted, clearly confusing the user.

**Comment by Marcono1234** [comment]
For tickets which are not reopened because they were resolved a long time ago (more than `softARDays`) this comment might be useful though to let the commenter know that they have to contact us.
But even then it would be good to check if such a comment was made (in the recent past).

**Comment by urielsalis** [comment]
What about not sending a comment about Keep AR if there was one sent previously?
