### ISSUE TITLE
Check whether a parent does have a specific link before transferring it over

### ISSUE THREAD

**Issue by miwob** [mojira/arisa-kt#302]
## The Bug
When transferring linked issues from a duplicate to its parent, arisa doesn't check whether the parent already does have this particular link set and just blindly adds it to the list causing a ticket to have the same link set multiple times.

## Example Ticket
[MC-165846](https://bugs.mojang.com/browse/MC-165846)

**Comment by NeunEinser** [comment]
> and just blindly adds it to the list

That's not true though.
Something faulty with this?
https://github.com/mojira/arisa-kt/blob/56e4d65567f23c9523bfa66d36906fc6537a4422/src/main/kotlin/io/github/mojira/arisa/modules/TransferLinksModule.kt#L28-L33

**Comment by SPGoding** [comment]
Also the duplicated link should be removed by the `RemoveIdenticalLinkModule` :thinking:
