### ISSUE TITLE
The duplicate comment is not posted when it should

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#305]
## The Bug
Relates to #304
Arisa did not post a comment after I resolved that ticket (I posted it a minute after myself then, Arisa did see the ticket for sure, as the version was transferred).

## Example Ticket
[MC-188592](https://bugs.mojang.com/browse/MC-188592)

## Expected behavior
Post comment

**Comment by urielsalis** [comment]
Doesn't arisa wait for 5 minutes?

**Comment by NeunEinser** [comment]
Really? Why?

**Comment by urielsalis** [comment]
In case the moderator puts the comment themselves, its there mostly so if we forget to do so there is still a comment

**Comment by urielsalis** [comment]
https://github.com/mojira/arisa-kt/blob/master/arisa.json#L72

**Comment by NeunEinser** [comment]
5 minutes seems a little excessive though, but sure ^^
