### ISSUE TITLE
Delete accidentally uploaded unzipped worldfiles

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#306]
## The Problem
Occasionally, it happens that a user uploads a world by dragging the world folder into the issue. That will cause all world files to be uploaded separately.

## Example Ticket
[MC-161823](https://bugs.mojang.com/browse/MC-161823)

## Possible Solutions
1. Add *.mca and *.dat to the attachment blacklist
This could have unwanted side effects though. It might be useful to upload a level.dat file sometimes, for example.
This could be solved by explicitly allowing level.dat somehow, however that would require an extension of the module
2. Command module for deleting attachments
Another soluting could be a command module that either purges all attachments from a ticket, or takes an extension as parameter.

**Comment by Pokechu22** [comment]
Maybe a command that purges all attachments from a given user (possibly also in a given time period)?

**Comment by miwob** [comment]
Since Arisa demands people to "only include crashlogs as text files and images as jpg or png instead of using a Word document" anyway, I'd rather replace the blacklist with a whitelist, or have a combination of both. Easier to manage & more strict as we don't deal with much file (formats) on the tracker.

**Comment by Marcono1234** [comment]
>This could have unwanted side effects though. It might be useful to upload a level.dat file sometimes, for example.
>This could be solved by explicitly allowing level.dat somehow, however that would require an extension of the module

There might be cases where attaching a `.mca` or `.dat` other than `level.dat` might be desired.
Instead I would suggest only having the module run if
> count(attachments (excluding `.png` and `.txt`)) > _threshold_

But then still apply the module to all the file types commonly found in world folders.
