### ISSUE TITLE
Language module: False negatives

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#337]
## The Bug
For some reason, some tickets don't get detected as being not in English correctly. Cause unknown.

## Example Ticket
https://bugs.mojang.com/browse/MCPE-84464
* Ticket was public at all times
* Ticket has more than 80 characters
* Dandelion detects the ticket's text as Russian

## Expected behavior
That ticket should have been resolved as Invalid by Arisa.

**Comment by SPGoding** [comment]
Pretty strange

The `combinedText` should be 
```
Здравствуйте разработчики есть проблема. Когда я играю в мир майнкрафт в выживание, без читов и с хорошим интернетом. У меня почему-то достижения не засчитываются в xbox. Я создал раздатчик - не за считалось, горшечник (я сделал 3 горшка и посадил в них цветы) - не засчитано. В чем может быть проблема?.
``` 
because the summary `Xbox` is included in the description. The response I got from Dandelion is 
```json
{"time":0,"detectedLangs":[{"lang":"ru","confidence":1.0}],"timestamp":"2020-06-21T17:12:04.672"}
```
So this should be perfectly resolved as Invalid :thinking:

Perhaps the ticket was somehow skipped, or there might be some errors when executing?

**Comment by urielsalis** [comment]
Did we see the module working correctly? It might be that we were unlucky enough that the ticket was created at the same time as the last run, so we fail the check that the ticket was created after last run

**Comment by NeunEinser** [comment]
> 
> 
> Did we see the module working correctly? It might be that we were unlucky enough that the ticket was created at the same time as the last run, so we fail the check that the ticket was created after last run

The time is saved *before* the run starts.
So the next run will see everything that happened *durin* the previous run.

**Comment by violine1101** [comment]
Another example: https://bugs.mojang.com/browse/MCPE-85607

**Comment by violine1101** [comment]
Another, more recent one: https://bugs.mojang.com/browse/MCL-14535

**Comment by urielsalis** [comment]
Are they later in the day? We might be running out of credits in dandelion

**Comment by violine1101** [comment]
First example was at 8AM UTC.
Second one at 9PM UTC.
Third one at 4AM UTC.

There doesn't seem to be any relation. What time zone does dandelion use?

**Comment by SPGoding** [comment]
Another example: https://bugs.mojang.com/browse/MCD-4258

**Comment by Jack-McKalling** [comment]
Another example: https://bugs.mojang.com/browse/MC-200465

**Comment by Jack-McKalling** [comment]
It happened again: https://bugs.mojang.com/browse/MC-206984

**Comment by urielsalis** [comment]
Closing as this hasnt happened lately and dandelion recently updated their model. We should create a new ticket if it happens again
