### ISSUE TITLE
Server crash reports are erroneously considered modded

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#34]
It appears Arisa incorrectly considers all server crash reports erroneously as modded.
Dedicated servers have the value:
```
Is Modded: Unknown (can't tell)
```

Example:
https://bugs.mojang.com/browse/MC-177440

Incorrect code:
https://github.com/mojira/arisa-kt/blob/9cce384da44760e3aed55b31183f37aea04546dc/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L109-L110

**Comment by Pokechu22** [comment]
Note that the value used on modded servers is <code>Definitely; Server brand changed to '<var>brand</var>'</code> (like with <code>Definitely; Client brand changed to '<var>brand</var>'</code> used on client crashes and most integrated server crashes (though, integrated ones can also find server brand changes if the client brand isn't changed... I don't think that situation ever comes up in practice though)).

They just don't have a META-INF signature check so there isn't a distinction between `Probably not` (which can be `Probably not. Jar signature remains and client brand is untouched.` or `Probably not. Jar signature remains and both client + server brands are untouched.`) and `Very likely; Jar signature invalidated` when the brand is unchanged.

**Comment by urielsalis** [comment]
So we should exclude "Unknown" or there is another suggesiton?

**Comment by Pokechu22** [comment]
Yeah, I think excluding both `Probably not` and `Unknown` is sufficient.
