### ISSUE TITLE
Automatically remove profanity/NSFW content from reports

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#342]
## The Problem
When profanity or NSFW content is used on the bug tracker, normally a mod/helper removes it from the report 
## Possible Solution
If Arisa was to do this, it would make the bug tracker a lot cleaner, and if possible, different words could be added to have the report still make sense.

**Comment by violine1101** [comment]
In my opinion this happens rarely enough for us to handle it manually. A NSFW filter would probably just have too many false positives to be useful.

**Comment by NeunEinser** [comment]
It could still be useful to make it not actively remove positives but to leave staff comments with a searchable tag.
That way, mods could make a filter for it and subscribe to that filter to receive emails whenever an issue is in that filter.

**Comment by Pokechu22** [comment]
IMO it's not worth doing this; I haven't seen many cases where profanity is included in reports.  And of course, the [Scunthrope problem](https://en.wikipedia.org/wiki/Scunthorpe_problem) makes a proper filter hard to implement.

**Comment by urielsalis** [comment]
Closing as Won't Fix then
