### ISSUE TITLE
Resolve tickets if they have a keyword from a different edition of the game

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#347]
If a report from one version had a keyword from a different edition of the game, Arisa could resolve the issue as invalid.
Example: Java Edition ticket with Xbox in the description
(Pocket Edition in the description could not be marked as invalid, because it could be a parity issue, but Pocket Edition in the Environment could be invalid)

**Comment by urielsalis** [comment]
Im scared of tickets like "This is different in Java" or "Works on Xbox but not in iOS", etc that might trigger this

**Comment by chandler05** [comment]
Could each filter be specific to each project?
"Works on Xbox but not in iOS" wouldn't really be an issue if filtering those keywords are exclusive to the java edition tracker
Also, the words Bedrock and Java could not be filtered at all because of parity issues

**Comment by chandler05** [comment]
The environment could work the same way, filtering out Xbox and iOS etc in the java edition tracker's environment field, but not in the bedrock edition's field

**Comment by Pokechu22** [comment]
Applying filtering to the environment field seems OK to me.  Doing it on the main issue text seems like it'd cause issues though.

For users that put the description in the environment, those tickets already need to be edited to fix that, so I don't think it's that big of a problem if they get resolved until they're edited.

**Comment by NeunEinser** [comment]
I don't know about this.
We for sure shouldn't scan the description for anything. E.g. [MC-163735](https://bugs.mojang.com/browse/MC-163735) contains the sentence `I played Minecraft on my Xbox and this isn't a problem there`.

**Comment by NeunEinser** [comment]
I don't really know how apple products work, and I am not sure if it's actually possible to install java on "iOS" vs "macOS", but in any case this seems to be a valid report for java mc, which was played on some kind of Apple device and has "mac iOS" in the enviornment: [MC-173425](https://bugs.mojang.com/browse/MC-173425)

**Comment by SPGoding** [comment]
I personally don't like the ideas of detecting general keywords in tickets to perform certain actions (like #66 and this suggestion), as human beings are bothering and they can organize words in the way that Arisa cannot expect and leads to false positives ;/

**Comment by NeunEinser** [comment]
I think this might be one that should be discussed on Slack with more people of the team, rather than just closing it.
I do see where the idea is coming from and using AR instead of Invalid may solve the problem in the regard of false positives.

That doesn't mean it's something I think we need for certain, but I am generally against closing issues single-handidly where there is at least some consensus of people who think it might be a good idea.
