### ISSUE TITLE
Crash module collects data which is never used

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#35]
The Crash module is currently a port without changing logic from the old arisa-js module.

For some reason, the crayh module collects the Java and the Minecraft version into a CrasInfo object, but nothing reads this data ever.

https://github.com/mojira/arisa-kt/blob/8dacad245e5237ced0039d3549f75975396f453d/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L141-L148

**Comment by urielsalis** [comment]
This is used in https://github.com/mojira/arisa-kt/blob/master/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L71

**Comment by NeunEinser** [comment]
Not java version or minecraft version though.
