### ISSUE TITLE
The crash module may fail to extract the exception in certain cases

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#36]
Currently the way arisa obtains the exception details from a crash report is extremely simple.
It just reads the 7th line (index 6):

https://github.com/mojira/arisa-kt/blob/8dacad245e5237ced0039d3549f75975396f453d/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L96
Even ignoring the fact Mojang may change the layout of a crash report at any time, since not just attached crash reports, but also attached launcher log files or a crash report added inside of the issue's description are evaluated, this already breaks there.
This means we probably should think of criteria/regex to match the exception header and then search for that line similarily to how other bits of information are extracted.

**Comment by urielsalis** [comment]
I would use this ticket as a rewrite of the crash module

Seeing the format in https://bugs.mojang.com/secure/attachment/169864/crash-2018-06-05_21.20.43-server.txt

You can split by sections (Marked by line starting in -- and ending in --), find the System details section

Inside it, you know that sections are key: value, so you can parse it and the find specific sections(if they exist)

It wouldnt survive a rewrite of the crash format but it would be way nicer than what arisa-js had

**Comment by urielsalis** [comment]
Fixed while rewritting the crash module
