### ISSUE TITLE
Arisa should disregard or delete modded crash reports which not attached by the reporter

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#360]
## The Bug
Arisa currently closes a ticket as Invalid if _anyone_ attaches a modded crash report.

## Example Ticket
https://bugs.mojang.com/browse/MC-173299

## Expected behavior
Either delete the modded crash report if it's not been attached by the reporter, or simply ignore it.

**Comment by NeunEinser** [comment]
I don't think the problem in your example was that someone other than the reporter attached a crash. The problem was that the bot did close the issue, even though one of the attached reports was not modded.
