### ISSUE TITLE
Users can add affected versions to reports they made duplicates of

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#362]
## The Bug
If a user adds an affected version to their resolved duplicate ticket, Arisa automatically adds that affected version to the new report.
This can be used by random users to add affected versions to Fixed tickets or add random versions to tickets that aren't theirs
## Example Ticket
https://bugs.mojang.com/browse/MC-193312 duplicate of https://bugs.mojang.com/browse/MC-191016
## Expected behavior
Users shouldn't be able to add these affected versions to tickets using their duplicates.

**Comment by NeunEinser** [comment]
> This can be used by random users to add affected versions to Fixed tickets

That part is not true -- Arisa never transfers versions to resolved tickets.

**Comment by urielsalis** [comment]
It shouldnt transfer version to resolved tickets and in open tickets mods are aware of this behaviour so they usually close invalid stuff as invalid instead of duplicates
