### ISSUE TITLE
FutureVersionModule: Only resolve tickets as Awaiting Response if the only affected version is a future version

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#365]
## The Bug
Arisa resolves the ticket completely if a Future Version has been added to the ticket but is not the only one. This causes the large text to be posted unnecessarily and is generally annoying.

## Example Tickets
* https://bugs.mojang.com/browse/MC-166718
* https://bugs.mojang.com/browse/MC-194906
* https://bugs.mojang.com/browse/MC-194940
* https://bugs.mojang.com/browse/MCPE-91458

## Expected behavior
Only resolve a ticket if the future version is the only one. If it's not the only one, only post the panel.

**Comment by SPGoding** [comment]
Fixed by #370
