### ISSUE TITLE
MissingCrash module is too naïve

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#376]
## The Bug
The MissingCrash module is too naïve and does not fulfil the requirements outlined in #66:

> False positives should be avoided, so perhaps the check should be a bit more sophisticated than [simply checking whether a ticket contains "crash" or not].

## Example Ticket
https://bugs.mojang.com/browse/MC-195379

## Expected behavior
Don't simply assume that a ticket is about a crash if it contains the word "crash". Examples:
* "My computer crashed and after that my world got corrupted!"
* "The server was running slow, but it did not crash"
* "After I died by crashing into a wall with my elytra my items were all gone"

**Comment by urielsalis** [comment]
as https://github.com/mojira/arisa-kt/issues/66#issuecomment-612654158 said, as its only AR those false positives are not that big. 

Do you have any suggestions on how the check would be improved?

**Comment by violine1101** [comment]
> Do you have any suggestions on how the check would be improved?

Not really, no. This is why I wanted to open the discussion in #66 first. I'm not even sure if this is possible to implement without significant amount of false positives, parsing natural language is not really trivial.

The reason why I think false positives should be avoided (even if tickets are only resolved as AR) is that in the end, false positives just cause more work for us than if Arisa wouldn't have done anything.

**Comment by chandler05** [comment]
Maybe instead of just "crash" it could look for "Minecraft crash" or "minecraft crashed"? It would remove some false positives...
