### ISSUE TITLE
ConfirmParentModule: Check for reporters of linked issues before setting a ticket to Community Consensus

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#378]
## The Bug
If a user duplicates their own ticket enough times and it's resolved as a duplicate by a mod, Arisa will set the original ticket to Community Consensus. (see #123)

## Example Ticket
Hypothetical issue, afaik there's no example ticket.

## Expected behavior
Only set a ticket to Community Consensus if at least one duplicate is by someone other than the reporter.

PS: In my opinion Arisa shouldn't mess with Confirmation status at all, but that's a different issue.

**Comment by SPGoding** [comment]
This has been discussed at #140; the module is based on the `Linked` field and it would be nearly impossible to check the reporter of each duplicates when updating that field.

Two potential solutions I could suggest:
1. Resolving duplicates of their own ticket as Invalid instead of Duplicate.
2. As violine mentioned in the post, disable the module.

**Comment by violine1101** [comment]
> Resolving duplicates of their own ticket as Invalid instead of Duplicate.

This is what I want to avoid, and is the reason for this post. Mods shouldn't need to change their workflows just to make the bot work correctly, it should be the other way round.

**Comment by NeunEinser** [comment]
> 
> 
> This has been discussed at #140; the module is based on the `Linked` field and it would be nearly impossible to check the reporter of each duplicates when updating that field.
> 
> Two potential solutions I could suggest:
> 
>     1. Resolving duplicates of their own ticket as Invalid instead of Duplicate.
> 
>     2. As violine mentioned in the post, disable the module.

I do see a third solution.
3. Don't use the linked field, but use the actual duplicate links, get the complete linked issue, and check the reporter.

**Comment by SPGoding** [comment]
I like that. Then is it still necessary to set the threshold to `3`?
