### ISSUE TITLE
Prevent non-volunteers from modifying the category of their own report

### ISSUE THREAD

**Issue by dericksonmark** [mojira/arisa-kt#380]
## The Problem
Users can modify the category of their own report, which can cause, in some cases, inaccurate categorization and can make it more difficult for developers who may use the category to assign a report to the proper person.

An example of this occurring can be found on my testing report [here](https://bugs.mojang.com/browse/MC-195635) (marked as private as so it does not interfere with bug tracker operations); feel free to remove the category from this report if you'd like (I'm just using it for testing purposes).

## How to Reproduce
I use Google Chrome as my browser and a MacBook Air as my computer. Reproduction steps may be slightly different in other browsers or computers. Also, I'm not sure if the Mojira interface is different for volunteers than it is for standard users, so I don't know if you'll be able to reproduce this.

1. Click Edit button on top left of a report created by you
2. Right click, then click Inspect
3. Press Shift+Command+C
4. Hover mouse over Mojang Priority, and see that you've selected `<div class="field-group">`
5. Click on class above that, should be `<div class="field-group" style="display: none;">`
6. Remove `style="display: none;"` from the line to make the category field visible
7. Click the small arrow in that line of text to reveal contents of the class
8. In `   <label for="customfield_11901">Category</label>
                <select class="select cf-select clientreadonly" id="customfield_11901" multiple="multiple" name="customfield_11901" size="5" data-remove-null-options="true" data-submit-input-val="true" data-input-text="" disabled="">`, change 'disabled' to 'enabled'
9. Now, close the inspector and select a category, and click Update. Notice that the changes appear on the page.

Unlike users changing Mojang Priority, this is a permanent change, meaning that even by refreshing the page the changes will be retained.

## Possible Solution
I'm not that good at code, but I'd assume that adding something to the module that prevents users from changing Mojang Priority could be used in the same way (reverts changes immediately after they're made).

_Hello! This is my first issue here, so I'm not so sure that this is in the right place or if it is even an issue at all._

**Comment by urielsalis** [comment]
Thanks for the report! The next time please submit a private WEB ticket in the tracker as this is public. We will get back to you :)

**Comment by dericksonmark** [comment]
Uh oh :/ I didn't think this was such a big issue (https://discordapp.com/channels/647810384031645728/648660584677769217/720629898087104552). Should I close this report?

**Comment by urielsalis** [comment]
dont worry, its already public and was reported before

**Comment by dericksonmark** [comment]
WEB-2789
