### ISSUE TITLE
Editing with vim/nano adds a new line to the end of last-run, making Arisa crash

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#392]
## The Bug
Editing with vim/nano adds a new line to the end of last-run, making Arisa crash
## Expected behavior
Remove any blank new lines before processing last-run to allow manual editing

**Comment by NeunEinser** [comment]
Weird, I edited last-run the other day using vim without any issues. But yeah, a potential crash caused by a new line doesn't seem very good 😂
