### ISSUE TITLE
Privacy module false negatives

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#401]
## The Bug
Some tickets containing Email aren't set to private by arisa.
## Example Ticket
https://bugs.mojang.com/browse/MCD-4250
## Expected behavior
Make the ticket private.

**Comment by NeunEinser** [comment]
I have no idea what went wrong there.

I set up a quick test, which passes (when replacing redacted with the actual stuff from the original description)
![image](https://user-images.githubusercontent.com/12124394/89136934-4f15cb00-d536-11ea-9e2e-b5aec0c79cc9.png)

**Comment by SPGoding** [comment]
Perhaps this is the same underlying issue as #337?

**Comment by NeunEinser** [comment]
My best guess is yes.
Recently we had another similar problem which was discussed on Discord, where Arisa wouldn't set CHK in one ticket. I ended up adding the ticket ID manually to last-run and restarting the bot, upon which the field was set.

There seems to be some tickets that do get missed. The time Arisa assumes for the current run, which ends up being stored as last-run is saved before the run starts, so in principle this shouldn't happen. Maybe there is a problem on jira's side though which means that tickets that were created or updated just as Arisa makes the request might not be fully updated and are not returned by the API during the run, even though they were technically updated before the run started and the timestamp that gets saved is also before the run.

Other than that I don't really have another idea of why this could happen.
