### ISSUE TITLE
Arisa does not remove Future Versions from resolved tickets

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#405]
## The Bug
When a user adds a future version to a resolved ticket, the version is not removed
## Example Ticket
Do it yourself ;)

## Expected behavior
It should be removed because it is an unreleased/future version

**Comment by SPGoding** [comment]
Note for other people who want to do this, this is what happened before: #313 and #314

Just add a check the the resolution in the module should be good enough.
