### ISSUE TITLE
Revoke changes done to Mojang Priority by users without permission

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#407]
## The Problem
See https://bugs.mojang.com/browse/WEB-2582

And I'm sure other ways to do this will be found

## Possible Solution
Revoke these changes if the users don't have the permission to do so

**Comment by dericksonmark** [comment]
Is Mojang Priority actually saved when users change it? It shows in the history that it's been changed, but the priority on the ticket is not really changed. You're a helper, so I think you can see my [testing ticket](https://bugs.mojang.com/browse/MC-195635).

There could just be another way to change the priority without the change being reverted immediately that I don't know of.

**Comment by chandler05** [comment]
Helpers can't view private tickets, so I can't see your ticket. Although, I have reported a way to do this that works for some users (as a private ticket) so it definitely is possible

**Comment by chandler05** [comment]
Well, it looks like these changes are no longer saved, so I'll close this issue.
