### ISSUE TITLE
Command for sending direct messages to users

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#421]
## The Problem
In some cases it would be useful to send a direct message to a user instead of having to comment on an issue which informs all watchers, even if the message is not relevant for them.

## Possible Solution
Jira provides the API endpoint [/rest/api/2/issue/{issueIdOrKey}/notify](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-notify) which can be used for this. This API endpoint sends an e-mail from the logged in account to users or groups.

### Considerations
- The e-mail is sent from Arisa, so it would be good to start the message with an indication which staff member created the message. However, it might also be useful to add an option for sending the message "anonymously" as "from staff" to prevent targeted attacks against staff members (depending on the context of the e-mail).
- The e-mail sent by Jira exposes the e-mail address of the user who used the API (i.e. Arisa) as `Reply-To` e-mail header. It would therefore be good to:
    - Not use a private e-mail address for Arisa
    - Not use Arisa's e-mail address for other purposes
    - Protect Arisa's account using [2FA](https://bugs.mojang.com/plugins/servlet/authplugin/tfaconfiguration) (?)

    Additionally since Arisa's e-mail address is used as `Reply-To` by Jira:
    - Arisa's mailbox should be checked a few times per week in case a user responds
    - The message sent by Arisa should have a footer stating
       > By responding to this e-mail your e-mail address will be shared with helpers and moderators of Mojira. They are volunteers and not Mojang Studios employees. Please only respond to this e-mail if you agree that your e-mail address is being shared with them. You can alternatively contact the helpers and moderators through the [Mojira Discord Server](https://discordapp.com/invite/rpCyfKV) or the [/r/Mojira subreddit](https://www.reddit.com/r/Mojira/) which both does not expose your e-mail address.
- Since the command becomes quite complex it would be good if Arisa edited the command message and added the execution feedback in front of the command (see also https://github.com/mojira/arisa-kt/pull/416#issuecomment-682845563).
- Before this feature is implemented it should be discussed with the Mojang devs, especially since they (likely) cannot trace these e-mails sent by the API. However, additionally the command could be configurable so it always sends a copy of the message to one (or multiple) of the Mojang developers by simply including them in the `users` value of the API request.
- When the command is used it should:
    - Send an e-mail to the staff member issuing the command (by including them in the `users` value of the API request) so they know that the command worked and see how the message looks to that user.
    - Send an e-mail to Arisa itself (by including it in the `users` value of the API request). This way it is more obvious afterwards which e-mails where sent by Arisa and it also gives context in case a user responds to an e-mail. However this apparently requires setting the Jira preference "My Changes: Notify me", otherwise it won't work. A solution to this could be (depending on the e-mail provider being used):
        - Add an e-mail filter to filter out all e-mail notifications for own changes (complicated and error-prone).
        - Create a second Mojira account which receives the copy of the e-mail (therefore not requiring "My Changes: Notify me"), but uses as e-mail address an alias / tag of the e-mail address used for Arisa's account (depends on e-mail provider), e.g. `arisa@gmail.com` and for the notification copy `arisa+sent-notifications@gmail.com`
- The Jira API endpoint has both `textBody` (plain text e-mail) and `htmlBody` (HTML e-mail). The command should use both values since it depends on the Jira preference "Email Type: Text / HTML" what the user will see. For the plain text e-mail formatting might become tricky.

### Proposed command syntax
The command could then look like this:
<pre>
ARISA_SEND_MESSAGE <i>[</i>-a<i>]</i> <i>RECIPIENT</i>
<i>SUBJECT</i>

<i>MESSAGE_BODY ...</i>
</pre>
- Command name: `ARISA_SEND_MESSAGE`
- Optional argument `-a` (anonymous):
    - If present: Prepends "From a helper / moderator:"
    - If not present: Prepends "From [Helper] XYZ:" / "From [Mod] XYZ:" (using the display name of the staff member issuing the command)
- <code><i>RECIPIENT</i></code>: User name who should receive the e-mail; note that some user names contain spaces so the recipient should be created using the remainder of the string on that line
- <code><i>SUBJECT</i></code>: E-mail subject. Jira only prepends "[JIRA]" to that. Maybe Arisa should add an additional "Message from staff: " so the result would be "[JIRA] Message from staff: <i>Some subject</i>"
- <code><i>MESSAGE_BODY</i></code>: Body of the e-mail; contains the remainder of the Arisa command comment. Should be separated using two line breaks (`LF` / `CRLF` / `CR`) from the subject.

### Body message format
Maybe it would be useful to allow formatting the message body. However, this formatting must in some way be displayable in the plain text e-mail as well (since that might be the Jira preference of the receiving user).

There are ways to render text as Jira HTML (though not sure how to display that for plain text e-mails):
- [Atlassian Wiki Renderer Maven artifact](https://mvnrepository.com/artifact/com.atlassian.renderer/atlassian-renderer?repo=atlassian-public); [Javadoc](https://docs.atlassian.com/atlassian-renderer/5.0/apidocs/com/atlassian/renderer/v2/V2Renderer.html) (probably outdated)
- Undocumented Jira [`/rest/api/1.0/render`](https://community.atlassian.com/t5/Jira-questions/Jira-Text-Formatting-to-HTML-JavaScript-Parser/qaq-p/607235#M201149) (note that the `issueKey` property shown in that example appears to not be necessary):
    - Unsupported, see also [JRASERVER-38731](https://jira.atlassian.com/browse/JRASERVER-38731)
    - Malformed input does not cause proper error but instead causes error string in resulting HTML (undesired!)

Otherwise we could support Markdown (but without embedded HTML; Arisa should escape that) or similar. This might look a little bit weird on the Jira Arisa command comment then, but Markdown has the advantage that it could be used as is for the plain text e-mail. One way to solve this would be to require having the e-mail message body inside a `{noformat}` block (<code>{noformat} <i>LINE_BREAK</i> <i>message</i> <i>LINE_BREAK</i> {noformat}</code>; <code><i>LINE_BREAK</i></code> = `LF` / `CRLF` / `CR`) in the command comment, this would then have the advantage that:
- Jira does not apply its formatting, which would be confusing
- It would be clear where the message body starts and where it ends

Maybe it would be good to pre-process the text to allow a line break (regardless of whether it has two spaces in front) to break the line. This is not the case for regular Markdown, but would make writing the text easier. E.g. use the regex `(?<!\R| )(\R)(?!\R| )` and replace every match with <code>&nbsp;&nbsp;\n</code> (SPACE SPACE LF). This transformation should not be performed for the plain text message body.

To differentiate the body from the header (mentioning the staff member who wrote the message, see note above) and footer (i.e. warning that e-mail address will be shared, see note above), it might be good to format the actual message body provided by the staff member in a special way, e.g. as block quote.

### Example
Here is an example, showing how a command and the generated e-mails could look like:
<details>
<summary>Jira command comment</summary>
<pre>
ARISA_SEND_MESSAGE john_doe
Don't ask for affected versions
{noformat}
Please do not comment on issues asking whether a version is still affected. These questions usually do not add much value and only unnecessarily notify all watchers. It would be more helpful if you instead tested whether the issue still occurs and then comment in case you can or cannot reproduce it.
Only we staff members ask this question from time to time because we don't always have the time to test whether an issue still exists.
{noformat}
</pre>
</details>

<details>
<summary>API request which Arisa would create</summary>
<pre>
{
    "subject": "Message from staff: Don't ask for affected versions",
    "textBody": "From [Mod] Marcono1234:\n&gt; Please do not comment on issues asking whether a version is still affected. These questions usually do not add much value and only unnecessarily notify all watchers. It would be more helpful if you instead tested whether the issue still occurs and then comment in case you can or cannot reproduce it.\n&gt; Only we staff members ask this question from time to time because we don't always have the time to test whether an issue still exists.\n----------\nBy responding to this e-mail your e-mail address will be shared with helpers and moderators of Mojira. They are volunteers and not Mojang Studios employees. Please only respond to this e-mail if you agree that your e-mail address is being shared with them. You can alternatively contact the helpers and moderators through the Mojira Discord Server ([1]) or the /r/Mojira subreddit ([2]) which both does not expose your e-mail address.\n\n[1] https://discordapp.com/invite/rpCyfKV\n[2] https://www.reddit.com/r/Mojira/",
    "htmlBody": "From &lt;b&gt;[Mod] Marcono1234&lt;/b&gt;:&lt;blockquote&gt;Please do not comment on issues asking whether a version is still affected. These questions usually do not add much value and only unnecessarily notify all watchers. It would be more helpful if you instead tested whether the issue still occurs and then comment in case you can or cannot reproduce it.&lt;/br&gt;Only we staff members ask this question from time to time because we don't always have the time to test whether an issue still exists.&lt;/blockquote&gt;&lt;hr&gt;&lt;sup&gt;By responding to this e-mail your e-mail address will be shared with helpers and moderators of Mojira. They are volunteers and not Mojang Studios employees. Please only respond to this e-mail if you agree that your e-mail address is being shared with them. You can alternatively contact the helpers and moderators through the &lt;a href=\"https://discordapp.com/invite/rpCyfKV\"&gt;Mojira Discord Server&lt;/a&gt; or the &lt;a href=\"https://www.reddit.com/r/Mojira/\"&gt;/r/Mojira subreddit&lt;/a&gt; which both does not expose your e-mail address.&lt;/sup&gt;",
    "to": {
        "reporter": false,
        "assignee": false,
        "watchers": false,
        "voters": false,
        "users": [
            {
                "name": "arisabot" // See notes above about sending e-mail to itself
            },
            {
                "name": "mojang_dev" // See notes above about informing Mojang
            },
            {
                "name": "john_doe"
            }
        ]
    }
}
</pre>
</details>

<details>
<summary>Result e-mail HTML</summary>
<p>(yellow outlined are the customizable parts)</p>
<img src="https://user-images.githubusercontent.com/11685886/91617508-81291a00-e988-11ea-8675-3ce188dbfa77.png" alt="Result e-mail HTML" style="max-width:100%;">
</details>

<details>
<summary>Result e-mail plain text</summary>
<p>(yellow outlined are the customizable parts)</p>
<img src="https://user-images.githubusercontent.com/11685886/91617745-f3016380-e988-11ea-89d7-abc82f1ddd05.png" alt="Result e-mail plain text" style="max-width:100%;">
</details>

## TODOs
- [x] Verify that the API works even if users are not watching an issue
- [ ] Verify that if multiple users are set as recipient they cannot see the e-mail addresses of other users in the e-mail sent by Jira

**Comment by urielsalis** [comment]
For the email we can always just use my domain and redirect there, it's safer as it's not a real email address they can try to hack while still redirecting to a Gmail account that we can access.

We could also technically lock it and make a bit that forwards answers to discord without the email

**Comment by urielsalis** [comment]
Thought a bit about this. We probably should make it so you have to create a private ticket in either MCTEST or STAFF instead of using a command

Ticket has a specific label and its standarized, then any answers to the email are sent as comments to the ticket, and we send new emails/answers ourselves via leaving a comment in the ticket


The hardest part is reading the emails to forward to the comment, but I can control fully where the email is received if we know of a good api or we just want to parse it ourselves

**Comment by urielsalis** [comment]
Closed after internal discussion
