### ISSUE TITLE
Fix Sentences That Have The First Letter Capitalized For Every Word

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#424]
## The Problem

Some Users Capitalize Every First Letter Of The Words In Their Bug Description, Which Makes It Fairly Difficult To Read. It Would Be Great If Arisa Could Edit Them To The Human-Friendly Format.

## Example Ticket

- [Https://Bugs.Mojang.Com/Browse/Mce-2612](https://bugs.mojang.com/browse/MCE-2612)

## Possible Solution

Use A Regular Expression To Match These Sentences To Decide If The Module Should Execute? I'm Not Actually Sure.

## Concerns

Some Letters That Should Actually Be Capitalized Might Be Lower-Cased By The Bot. It Shouldn'T Be A Big Deal Though. We Could Do A Special Case For The Single Letter "`I`".

**Comment by NeunEinser** [comment]
A whitelist for words might be good. Apart from `I`, names such as `Minecraft` or `Mojang` come to mind.

**Comment by NeunEinser** [comment]
Or alternatively, the module could require a certain percentage of capitalized words, to avoid lowercasing stuff that was intentionally put in uppercase.

**Comment by dericksonmark** [comment]
If Possible, The Module Should Also Make Sure That It Is Not Changing The Capitalization Of Words Within Links Or Code, As That Could Lead To Incorrect Reproduction Of The Issue. For Example, Links Could Be Case Sensitive And Should Not Be Corrected By The Module. 

Also, Words Like I'd, I'll, I'm, And I've Should Be On The Whitelist Too (The Whitelist Mentioned In NeunEinser's First Comment).

The Module Could Also Not Change The Capitalization After An Edit To The Description. If Arisa Made A Mistake And The Reporter Needs To Correct It, They Should Be Able To Without Their Changes Being Reverted.

I Don't Like Writing Like This. :(

**Comment by NeunEinser** [comment]
Regex `\b` can be used as word boundary. Apostrophes do count as boundary, so you don't have to define those manually.

**Comment by MikeUnverferth** [comment]
Could it also fix cases where at least the summary USES ALL UPPERCASE?

**Comment by chandler05** [comment]
Discussed and decided not to implement this
