### ISSUE TITLE
Set Linked field to 0 when it is empty

### ISSUE THREAD

**Issue by dericksonmark** [mojira/arisa-kt#426]
## The Problem
When volunteers change the Linked field, they completely empty it if the value reaches 0 [(Example)](https://bugs.mojang.com/browse/MC-3610). This can happen when a ticket was marked as a duplicate of it but that resolution was later deemed incorrect. When Arisa does this, the field is not completely emptied, leading to Linked = 0 [(Example)](https://bugs.mojang.com/browse/MC-137452). Yes, this is an extremely minor issue.
## Possible Solution
Check tickets for Linked = 0, and when found, empty the field.

**Comment by NeunEinser** [comment]
I still think it would be better to have it default to 0, as that's better for sorting. NULL values mess up the sort, so you always have to filter for Linked != EMPTY if you want a reasonable result.

If this is implemented, there is no reason to search for linked 0 fields, but instead the Linked module should just set it to null right away. Only volunteers can edit that field. so no regular user can "mess it up"

**Comment by MikeUnverferth** [comment]
Yes, making the field numeric and defaulting to 0 would make sorting on Linked useful without having to also filter.
