### ISSUE TITLE
Automatically change platform to "multiple" if linked duplicate has different platform

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#431]
## The Problem
Most bugs are not platform-specific, but the reporter should usually choose their own platform. It takes time to then look at the duplicates to see if they reference a different plaform

## Possible Solution
Automatically change platform to "multiple" unless MEQS_KEEP_PLATFORM is set (Issue #430) and a duplicate is linked with a different platform

**Comment by MikeUnverferth** [comment]
I don't think we should release this until the MEQS_KEEP_PLATFORM is handled otherwise we may get some unwanted changes to multiple.

**Comment by chandler05** [comment]
I added in the MEQS_KEEP_PLATFORM command to the Pull Request and it should now be ready for review
