### ISSUE TITLE
MEQS_STOP_COMMENTS to remove any unwanted comments added to specific reports

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#434]
## The Problem
Some tickets get so popular, that they end up with Moderator Panels etc. saying that they should be discussed on the subreddit. Other tickets are old and Invalid, but there is no reason to delete them. Both of these cases make these tickets targets for dumb comments and random comments. In both of the cases we could use a MEQS_STOP_COMMENTS command to delete any comments added to these reports.
## Possible Implementation
Allow helpers, moderators, staff and potentially the reporter to comment on the ticket, but delete (or restrict?) all other comments

**Comment by NeunEinser** [comment]
There is the status called "Closed" which prevents comments and it was removed from the workflow for a reason.

I don't think it's a good idea to generally forbid all comments on an issue ever.
Note that panels like you describe are always related to comments that are irrelevant to the report, like discussion the validity of a ticket or disagreeing with a resolution. It's a bug tracker not a discussion forum.
Comments that *are* relevant to the report are *always* okay though.

**Comment by chandler05** [comment]
When I referenced the Moderator Panel, I was referring to MC-108, which I don't think has any reason to be commented on?
The comment could also be placed on tickets like MC-69 if they're resolved as Invalid. Usually there's not a good reason to comment on ticket numbers like that unless its a joke.

**Comment by MikeUnverferth** [comment]
Back in the day when there were far fewer Mojira users and the incoming reports were of higher average quality, it was likely to have been easier to keep up on all incoming input, including comments on any unclosed ticket. Nowadays, just keeping up with newly created reports is difficult. For most resolved tickets, there is little reason, if any, that comments should be needed. In the rare case of someone asking that a ticket be reopened, using Discord or reddit is always available, and is much more likely to be noticed. I wonder if it would be possible to revisit the issue of restoring the ability to close most resolved tickets? I think this would be better overall than having a bot remove potentially helpful comments on open tickets.

**Comment by urielsalis** [comment]
If we get into issues with a specific ticket, we can always request that its set to "Closed", we dont need Arisa for that

and anyway, this is something that has to be discussed with Mojang first
