### ISSUE TITLE
Arisa leaves empty comments

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#435]
## The Bug
Arisa sometimes leaves empty comments

## Example Tickets
https://bugs.mojang.com/browse/MCPE-100371
https://bugs.mojang.com/browse/BDS-9005

## Expected behavior
It should have left a comment about the ticket being not in English

**Comment by chandler05** [comment]
AHA! its the word "nova" throwing Arisa off because it means "new" in Portuguese, but is considered a pirated launcher! Should "nova" be removed from the Piracy module?

**Comment by chandler05** [comment]
Or maybe it'd just be better to fix the actual bug :|

**Comment by urielsalis** [comment]
Merged into #527

**Comment by chandler05** [comment]
They are not the same, this has a different cause
