### ISSUE TITLE
Automatically remove intermediate beta versions from Affected Versions after release.

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#439]
## The Problem
Some tickets have a large number of beta/snapshot Affected Versions entries. This just adds unnecessary clutter to some tickets. For example: https://bugs.mojang.com/browse/MCPE-31896

## Possible Solution
Automatically remove all beta/snapshot entries that occur between two "release" versions.

**Comment by SunCatMC** [comment]
afaik archived versions can't be removed tho, not even with api

**Comment by MikeUnverferth** [comment]
That's unfortunate. Perhaps we need to be more selective about adding beta/snapshot affected versions then?

**Comment by chandler05** [comment]
See #425, archived versions cannot be removed even using the API, as SunCat said

**Comment by urielsalis** [comment]
I dont think we should be removing affected versions either way, but closing as we cannot remove them using API
