### ISSUE TITLE
Add ARISA_DUPLICATED_BY command for bulk resolves

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#442]
## The Problem
Often there are many duplicates reported for certain bugs. These can be bulk resolved already using a sequence of Mojira steps, but it would be easier to do via a single command

## Possible Solution
Add ARISA_DUPLICATED_BY key1,key2,...
1. Resolve all of the listed tickets as duplicates.
2. Add standard message if needed.
3. Add is-duplicated-by link from ticket containing command

Should have some validation so that undesirable cross-project duplication is prevented, but certain cases are allowed. Also would obviously want to ignore already-resolved tickets.

I had previously proposed creating a web page that would do this via the API. An advantage of that approach would be that it would be done as the user (mod) submitting the request instead of as "Arisa", which would allow followup if there's a question. Doing as Arisa command is probably much easier though.

**Comment by SunCatMC** [comment]
ty for the idea, already working on ARISA_ADD/REMOVE_LINKS, so this could be a variation of that =P

**Comment by SunCatMC** [comment]
The only issue is that currently only outwards links are supported, like "duplicates", but maybe with additional code it could be fixed

**Comment by SunCatMC** [comment]
actually added the functionality, after merging the pull request gonna start working on this command =)

**Comment by urielsalis** [comment]
@SunCatMC if you are working on it, assign yourself the issue :D

**Comment by SunCatMC** [comment]
technically not yet, but gonna do so when I finish the pull request, and I'm already thinking on it

**Comment by SunCatMC** [comment]
BTW, now thinking about this issue, you would still need access to other tickets to resolve them as dupe, so this needs a bit more internal work

**Comment by SunCatMC** [comment]
what kind of cross-project duplication would be undesirable?

**Comment by urielsalis** [comment]
REALMS -> MC, MCPE
MC -> MCL
MCPE -> BDS

**Comment by SunCatMC** [comment]
looks like in practice both directions are used (MC -> MCL and MCL -> MC)

**Comment by urielsalis** [comment]
Thinking about this, its quite easy already to do bulk duplicates, not sure if a command is worth it

**Comment by violine1101** [comment]
I'd agree. It's pretty easy by doing it this way:
* Get a list of tickets you want to resolve
* Use a filter like `key IN (MC-1, MC-2, MC-3)` to get a filter with all the issues in the list
* Use bulk resolve to duplicate
* Go to the parent ticket
* Click on Update/Edit/Link
* Paste the list (space separated) into the "Issue" field and change link type to "is duplicated by"

It's a bit cumbersome, but since this is only rarely used I personally don't think a command is needed either.
