### ISSUE TITLE
Add ".pkg" to the attachment extension blacklist

### ISSUE THREAD

**Issue by pine1needle** [mojira/arisa-kt#460]
## The Problem
Recently, a suspicious user added a ".pkg" file to [MC-192591](https://bugs.mojang.com/browse/MC-192591) as an attachment. The name of the attachment said that it was a resource pack, but the purported resource pack wasn't related to [MC-192591](https://bugs.mojang.com/browse/MC-192591) at all, and resource packs aren't distributed as ".pkg" files anyway. Arisa did not remove this file and a mod removed it instead. In the future, Arisa should probably remove ".pkg" files automatically.
## Context
Multiple operating systems are able to install software using files with the ".pkg" file extension. See the [Wikipedia article](https://en.wikipedia.org/wiki/.pkg) for details.

**Comment by SPGoding** [comment]
Let's just use a whitelist :rofl:

**Comment by urielsalis** [comment]
no whitelist :eyes:
