### ISSUE TITLE
Arisa should mark .rar and .class files as disallowed file extensions

### ISSUE THREAD

**Issue by Chungui23** [mojira/arisa-kt#474]
In the title ^

**Comment by dericksonmark** [comment]
Hello! RAR files are not always malicious, and are attached to many reports non-maliciously. So they should probably not be added to the exclusion list.

**Comment by urielsalis** [comment]
And I would argue you can't execute .class manually

**Comment by Chungui23** [comment]
but .class files can be harmful, just like .jar files

**Comment by urielsalis** [comment]
Someone that knows how to run a .class manually knows to not do it

**Comment by pine1needle** [comment]
I'm neither arguing for nor against adding ".class" to the exclusion list, but I believe having example tickets for issues like this is helpful, so here's an example where a suspicious user added a ".class" file to a ticket and a mod had to remove it manually: [MC-187515](https://bugs.mojang.com/browse/MC-187515)

**Comment by Chungui23** [comment]
also, Arisa should mark .pax or .cpio files as disallowed file extensions

**Comment by SPGoding** [comment]
I'm personally not a fan of disallowing any archive formats

**Comment by pine1needle** [comment]
Again, I'm neutral, but here's an example ticket where a suspicious user uploaded a ".cpio" file and a mod had to remove it: [MC-202554](https://bugs.mojang.com/browse/MC-202554)

**Comment by violine1101** [comment]
For rare file formats like this it usually is not much effort to remove potentially malicious files manually. The bot handles the more common file formats that are more likely to be malicious (i.e. files that can be directly executed, which is not the case for .rar or .class).
