### ISSUE TITLE
Incorrectly sets version to an "archived" beta instead of a current released version when rejecting "future release".

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#476]
## The Bug
When Arisa rejects an unreleased "future" version, it incorrectly sets the version to an archived beta. The problem with that is that neither the reporter, nor a mod, can then remove that version when correcting to the actual release, leading to incorrect information.

## Example Ticket
https://bugs.mojang.com/browse/MCPE-103288

## Expected behavior
Arisa will choose either the latest non-beta release, or the latest beta release.

**Comment by urielsalis** [comment]
https://github.com/mojira/arisa-kt/blob/9c17ff69b856ec024aa83f2c11426e65a9f0fe5a/src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt#L62 Arisa checks expliclitly that the version is not archived or not released, was it incorrect in jira?

**Comment by MikeUnverferth** [comment]
Idk how I would check if it was incorrect in Jira? I just noted that the version got set to 1.16.100.59 beta _after_ the .60 beta was released. Now (and on 21 Oct also), I was not able to remove the .59 beta entry, even though it is incorrect as the bug specifically is for the RTX beta only.

**Comment by MikeUnverferth** [comment]
Did the same thing today to https://bugs.mojang.com/browse/MCPE-103593 where it changed to 1.16.100.59 beta instead of what is currently the latest 1.16.200.51 beta.

**Comment by Marcono1234** [comment]
@urielsalis the problem might be that it is using the complement to select the `latestVersion`:
https://github.com/mojira/arisa-kt/blob/9c17ff69b856ec024aa83f2c11426e65a9f0fe5a/src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt#L24

`!(!version.released && !version.archived) = version.released || version.archived`

The question is why it is checking for archived versions in the first place, but https://github.com/mojira/arisa-js/commit/fa004c5acf8d3fdc65c10d3ec5f02e9950ffccbb suggests that there are versions which are archived but not released.

So maybe the solution would be to only consider released versions (but ignore archived versions) when searching for `lastestVersion`.

**Comment by SunCatMC** [comment]
I happened to not read the explanation and came to the same conclusion
