### ISSUE TITLE
Send different comment in Duplicate Message Module when the ticket is forward resolved

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#478]
## The Problem
Arisa sends the same comment for tickets that get forward-resolved, creating confusion and annoyance for our beloved players.

## Possible Solution
Check the `created` time of the parent and the child to determine if she needs to send the alternative message.

**Comment by Marcono1234** [comment]
The message is added by https://github.com/mojira/helper-messages/pull/123, correct?

**Comment by SPGoding** [comment]
Yes.
