### ISSUE TITLE
Add ".saver" to the disallowed attachment extension list

### ISSUE THREAD

**Issue by pine1needle** [mojira/arisa-kt#483]
## The Problem
Recently a suspicious user added a ".saver" file to [MCPE-71243](https://bugs.mojang.com/browse/MCPE-71243) as an attachment. In the future, Arisa should probably remove ".saver" files automatically.
## Context
According to [Wikipedia](https://en.wikipedia.org/wiki/Screensaver#MacOS), ".saver" files are used for screen savers on MacOS. I am unsure whether it is possible for files of this type to be malicious, but the [Apple developer documentation](https://developer.apple.com/documentation/screensaver/screensaverview) implies that these files are code (not just videos), so it seems plausible that they could be malicious. Additionally, I doubt that there would ever be a situation where a ".saver" file would be relevant to a bug report.

**Comment by Jack-McKalling** [comment]
Correct, screensavers can have malicious code. I would however, concern myself with restricting what files types are allowed, rather than what is not. Because there is a lot less of those.

**Comment by pine1needle** [comment]
I believe having a disallowed list is better than having an allowed list because missing file extensions in a disallowed list result in false negatives and missing file extensions in an allowed list result in false positives. False positives are much worse than false negatives because it is much harder to try to recover an attachment that was erroneously deleted by Arisa than it is for a mod to remove an attachment that was missed by Arisa.
