### ISSUE TITLE
RemoveIdenticalLink module removes both links

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#487]
## The Bug
RemoveIdenticalLink module removes both links.

## Example Ticket
https://bugs.mojang.com/browse/MC-199657?focusedCommentId=817403&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-817403

## Expected behavior
Only remove one of the two relates links. (Perhaps always the outwards one?)

**Comment by urielsalis** [comment]
Is this still happening? we seem to test that we only remove one of them

**Comment by violine1101** [comment]
This has probably been fixed in #311.

**Comment by SPGoding** [comment]
Nah not the same. Before #311 two identical relates to links (one inwards and one outwards) can exist on the same ticket, #311 fixed that. However, when the module runs on both affected tickets, both relates links are removed, which is what this issue is about.
