### ISSUE TITLE
Support deletion of Arisa comments

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#488]
## The Problem
In some cases comments by Arisa are incorrect or redundant. Usually we then reduce their visibility to not confuse users and to remove clutter in the comment section for normal users. However, we staff members still see the comments which can be annoying sometimes.

## Possible Solution
It should be possible to have Arisa delete its own comments. Internally it was discussed that merely requiring a different comment visibility does not suffice because in some cases it might be desired to keep the comment.
Instead it has been suggested that Arisa comments with the text `ARISA_DELETE` (irrespective of visibility) should be deleted.

To prevent unnecessary update notifications, staff members are encouraged to both change the comment to `ARISA_DELETE` and reduce its visibility at the same time.

### Considerations
As described in [WEB-2773](https://bugs.mojang.com/browse/WEB-2773) normal users still see (and are notified about?) the deletion of a comment with restricted visibility.

The complete body of the comment has to be `ARISA_DELETE` (instead of only checking if it is contained), otherwise malicious users might be able to insert this substring, for example through attachments with disallowed extension whose name contains this string.

**Comment by Marcono1234** [comment]
@DrAwesome4333, you have a valid point with your (now deleted) comment here about the used jira-client not offering a way to delete a Jira comment. I am not seeing such functionality either.
Maybe we would manually have to perform the [REST call](https://docs.atlassian.com/software/jira/docs/api/REST/8.19.1/#issue-deleteComment) using the authenticated HTTP client instance; though that might not be worth it.

**Comment by DrAwesome4333** [comment]
@Marcono1234 I actually managed to get a working module for deleting comments by using a the same code that deletes attachments. I have a current branch on this fork [here](https://github.com/DrAwesome4333/arisa-kt/tree/RemoveBotComment).
I also should take time to fully think something out before I comment so sorry about that. (I have a bad habit of commenting something, then realizing it was a question I could have answered myself then deleting said comment)
