### ISSUE TITLE
Role accounts should not cause a ticket to be marked as private

### ISSUE THREAD

**Issue by sebastiannielsen** [mojira/arisa-kt#490]
## The Bug
Write a role account - for example abuse@example.org
Ticket is marked as private.

## Example Ticket
https://bugs.mojang.com/browse/MCPE-107940

## Expected behavior
Role accounts - those defined in RFCs are per definition public, and should never cause a ticket to be marked as private.
Role accounts are the following:

mailer-daemon@<domain.tld>
postmaster@<domain.tld>
nobody@<domain.tld>
noreply@<domain.tld>
no-reply@<domain.tld>
hostmaster@<domain.tld>
usenet@<domain.tld>
news@<domain.tld>
sales@<domain.tld>
marketing@<domain.tld>
webmaster@<domain.tld>
www@<domain.tld>
abuse@<domain.tld>
noc@<domain.tld>
security@<domain.tld>
info@<domain.tld>
support@<domain.tld>
uucp@<domain.tld>
ftp@<domain.tld>
news@<domain.tld>
admin@<domain.tld>
root@<domain.tld>

Technically it can be done by creating a copy of the ticket text in a new variable, then use a regexp to remove ALL role-acocunt emails (like: s/(mailer-daemon|postmaster|nobody|noreply|no-reply|hostmaster|usenet|news|webmaster|www|abuse|noc|security|info|support|uucp|ftp|news|admin|root)\\@//gi) and then check with filters, if the remaining text now contains any private info.

**Comment by Pokechu22** [comment]
Which RFC specifies that list?  I was unable to find one.  (The actual idea seems reasonable though)

**Comment by sebastiannielsen** [comment]
Here is a decent list specified in RFC2142:
https://www.ietf.org/rfc/rfc2142.txt

**Comment by urielsalis** [comment]
Merged into #541
