### ISSUE TITLE
Add a comment that stops arisa from posting the 'duplicate' message

### ISSUE THREAD

**Issue by Greymagic27** [mojira/arisa-kt#492]
## The Problem
In some situations you may not want the 'duplicate' message to be posted
## Possible Solution
Make a comment that helper+ can use to stop the message from being sent

**Comment by urielsalis** [comment]
Can you elaborate on which cases you dont want it to be posted? If you post the message yourself (or any user did), Arisa will not post it

**Comment by Greymagic27** [comment]
In cases when people have duplicated their own issue is what i was thinking

**Comment by urielsalis** [comment]
I don't think is that big of a deal and it would be annoying to put the command each time

**Comment by Greymagic27** [comment]
Yeah, I agree with that.

Looking back they'd be nearly no cases where this would be needed

**Comment by SPGoding** [comment]
A case where this is needed: https://bugs.mojang.com/browse/MC-88297

I changed the duplicate link on an ancient report upon the request of Connor. The bot will create the duplicate comment as neither of the parents were mentioned before.
