### ISSUE TITLE
Add command to stop reopening of AR tickets unless original reporter responds.

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#493]
## The Problem
Often A-R tickets are asking for specific information from the original reporter, such as exact messages they are seeing, steps to reproduce the issue, etc. Arisa reopens tickets when anyone responds, which is sometimes helpful, especially for bulk resolves, but for individual requests not so much.

## Possible Solution
Add ARISA_REOPEN_ANY to reopen if anyone responds. Default behavior would be to reopen only if the OP responds.

**Comment by MikeUnverferth** [comment]
For extra robustness, it could also reopen if the OP for any Linked ticket responds.

**Comment by urielsalis** [comment]
It should be the opposite, ARISA_REOPEN_OP if only OP should be allowed to reopen
