### ISSUE TITLE
Exempt Mojang employees from the Privacy module

### ISSUE THREAD

**Issue by Jack-McKalling** [mojira/arisa-kt#497]
## The Problem
When a mojang employee makes a comment that contains an email address (as far as Arisa knows), the comment gets unnecessarily restricted, quite like here:
https://bugs.mojang.com/browse/MCPE-105882?focusedCommentId=858817&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-858817

## Possible Solution
We should be trusting the owner of the platform not to post privacy-sensitive information, so mojang employees should be exempted from the check. Alternatively, the other way around, the module could be configured to specifically function only on e.g. the user, helper and moderator groups. That way no exception-logic is needed.

**Comment by urielsalis** [comment]
should be excluding anyone on the correct groups, same as the other modules
