### ISSUE TITLE
Only restrict email addresses of certain TLDs

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#500]
## The Problem

Relates to #490.

`inventory_selected_icon_button@common.inventory_selected_icon_button` is seen as an email address.

## Possible Solution

Only restrict email addresses of certain common TLDs, e.g. `com`, `net`, `org`, `edu`, etc. I don't see the reason to add all new TLDs to the list (e.g. `xyz`, `io`, etc.).

**Comment by Marcono1234** [comment]
Or restrict the TLD to a regex similar to `[a-zA-Z]{1,4}`, that might already prevent most false-positives.
