### ISSUE TITLE
Restrict Arisa responses to commands to "staff" instead of "helper"

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#502]
## The Problem
Currently responses are restricted to "helper". However, the helpers correctly cannot see the actual commands since they are staff-restricted. This is likely to be confusing to helpers.

## Possible Solution
Restrict responses to staff group instead of helper.

**Comment by chandler05** [comment]
Duplicate of #404

**Comment by MikeUnverferth** [comment]
I searched for a duplicate! Really I did. :(
