### ISSUE TITLE
PrivacyModule: False negative if email address is in a link

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#506]
## The Bug
The `PrivacyModule` doesn't trigger if the email address is in a link (example: `[test@example.com|mailto:test@example.com]`).

## Example Ticket
https://bugs.mojang.com/browse/MC-210895

## Expected behavior
The module should trigger.

**Comment by violine1101** [comment]
Another false negative to consider: https://bugs.mojang.com/browse/MC-211676

**Comment by chandler05** [comment]
I'm pretty sure this is due to #390, which made the module not mark an email as private if it ends with a closed square bracket for mentions. Since usernames with emails are being removed, I think it is best to mark emails in mentions as private again, fixing this as well

**Comment by chandler05** [comment]
I'm pretty sure this is due to #390, which made the module not mark an email as private if it ends with a closed square bracket for mentions. Since usernames with emails are being removed, I think it is best to mark emails in mentions as private again, fixing this as well
