### ISSUE TITLE
Email addresses used by Mojang shouldn't be restricted

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#510]
## The Bug

Relates to #490 and #500.

## Example ticket
[https://bugs.mojang.com/browse/MC-211171?focusedCommentId=896562&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-896562](https://bugs.mojang.com/browse/MC-211171?focusedCommentId=896562&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-896562)

## Expected behavior
Don't restrict emails ending with `microsoft.com`, `minecraft.net`, `mojang.com`, and `zendesk.com`? We could use a regex to remove those domains from the text before checking, similar to what being suggested at #490.

**Comment by urielsalis** [comment]
Merged into #541
