### ISSUE TITLE
Automatically updating report priority if it is empty

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#52]
Moving a report from any project to WEB without updating the priority causes the priority field of the report to stay empty. Arisa could set this field to the default "Minor" priority if it is empty.

See [`project = WEB AND priority = EMPTY`](https://bugs.mojang.com/issues/?jql=project%20%3D%20WEB%20AND%20priority%20%3D%20EMPTY).

Moved from https://github.com/mojira/arisa-js/issues/8

**Comment by urielsalis** [comment]
https://github.com/mojira/arisa-js/pull/9/files might be a good start

**Comment by NeunEinser** [comment]
Just tested this, is this still valid?
It sets priority when moving now, and you can't change it to an empty value.
![image](https://user-images.githubusercontent.com/12124394/78674453-edc15080-78e3-11ea-9bbd-53d5690b55cc.png)

**Comment by urielsalis** [comment]
Awesome. Closing
