### ISSUE TITLE
Arisa does not detect emails when they're edited in after creation

### ISSUE THREAD

**Issue by Greymagic27** [mojira/arisa-kt#525]
## The Bug
After editing in an email onto a ticket, arisa will not detect that and will not make the ticket private.

## Example Ticket
https://bugs.mojang.com/browse/MC-213477

## Expected behavior
To make the ticket private.

**Comment by Greymagic27** [comment]
Manage to repro the results on https://bugs.mojang.com/browse/MC-213537

**Comment by chandler05** [comment]
From what I understand the module was specifically built to where this would not trigger the privacy module, but I have not idea why

**Comment by SPGoding** [comment]
> The module should only work on issues that have been created since the last run (in case a moderator purposefully set it to public, Arisa should not set it to private again).

From #227.

If we were to check edits as well, we'd have to check if the email address is introduced in the last update. There might also be some other cases that would cause false positives that I can't think of for now.

**Comment by urielsalis** [comment]
The idea of only checking on initial creation is that if it misfires it doesnt keep marking it as private after we revert it

**Comment by violine1101** [comment]
I'd agree here, this happens rarely enough that this should not be changed imo; it's more important to be able to revert false resolutions.
