### ISSUE TITLE
 Prevent users from publishing their session id

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#53]
Even though the launcher and the client were changed to not include the session id anymore, there are still people playing with old launchers old versions of the game (or the new launcher does not censor it?).

It would be good if Arisa could prevent people from

putting the session id in the description
writing the session id in a comment
attaching a log file which contains the session id
The log line would have the prefix (Session ID is and would be (Session ID is <censored>) if it was censored by the old Java launcher.

Moved from https://github.com/mojira/arisa-js/issues/12

**Comment by urielsalis** [comment]
Do we think we still need this?

**Comment by violine1101** [comment]
As far as I'm aware, the session ID is no longer visible in the launcher log, and the current version of the launcher does try to hide it if you're launching an older version of the game. Therefore, this module would only apply to game logs from old versions where the game has been launched with an outdated third-party or the old 'vanilla' launcher.

I've not seen a session ID on Mojira in ages (but then again, I also haven't explicitly looked for one).

**Comment by violine1101** [comment]
Then again, it wouldn't be a difficult thing to implement, it's just simple string replacement if you disregard attachments. And apparently there are a few recent cases where the session ID is not censored, although they seem to be quite rare.

**Comment by Pokechu22** [comment]
The session ID is logged at debug level in current versions (I'm not sure when it was changed, but it was a few years ago), which means it's hidden by default but could be found if that's enabled.  I'm not sure if it's hidden in the actual launcher debug log or not nowadays.

I'm not sure what Arisa could do in this case, though; if it's an attachment it could delete it but if it's in the ticket, it can only be edited and the ID would still be in the edit history.  Plus arisa would probably post a comment, which would just draw attention to the fact that there was a session ID at some point...

**Comment by violine1101** [comment]
Maybe it should just set the ticket to private then?

**Comment by Marcono1234** [comment]
It appears the new launcher correctly censors the the session id logged by older versions (e.g. 1.8.1) in the "Minecraft game output" and in the launcher log, though it logs two large hex blocks with the prefix "[DATA]", which slightly worries me.
However, the game log file still contains it uncensored (see also [MCL-4420](https://bugs.mojang.com/browse/MCL-4420)).
Though the number of people playing such an old version and attaching a log file for it is probably really low, so I would not mind if we close this issue.

**Comment by NeunEinser** [comment]
> Maybe it should just set the ticket to private then?

If we add this module that would probably the way to go, yes.
