### ISSUE TITLE
Use warn severity for some common exceptions

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#534]
## The Problem
#arisa-error-log is spammed with exceptions like `net.rcarz.jiraclient.RestException: 502 Proxy Error`, which is actually quite unhelpful.

## Possible Solution
Catch certain types of exceptions and log them as `warn` instead?

**Comment by urielsalis** [comment]
For that specific one (and connection errors with Jira), I would use a throttled log every 30 mins that just says "Failed to connect to jira".

Posted once every 30 mins as long as it continues
