### ISSUE TITLE
ReopenAwaitingModule: Ignore activity for a certain amount of time after having resolved the ticket

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#56]
Example: https://bugs.mojang.com/browse/MCD-300

It would be great if Arisa would just ignore updates for a certain amount of time after a ticket has been resolved as AR in case the person who resolved the ticket wants to add a comment, link the ticket, or similar. Optimally, it would only ignore updates by the person resolving the ticket, not by others, but I don't know how easily this can be implemented.

**Comment by NeunEinser** [comment]
I don't immediately see any problems with checking who made the change.

I think Arisa probably should ignore all of those:
* Any change made by someone of group `global-moderators` or `staff` (If they have an answer, they can just reopen themselves easily)
* Any comment restricted to `helper`, `global-moderators` or `staff`

**Comment by urielsalis** [comment]
> Any change made by someone of group global-moderators or staff (If they have an answer, they can just reopen themselves easily)

It might be useful to have those as triggers, for example for https://github.com/mojira/arisa-kt/issues/50

**Comment by NeunEinser** [comment]
What do you mean by trigger in this context?

**Comment by urielsalis** [comment]
a comment or resolve might trigger a module in a old ticket and slowly clean up

**Comment by urielsalis** [comment]
Plus that module requires explicitly that the action was done by a mod, so we cant ignore it

**Comment by NeunEinser** [comment]
I still don't know what you are talking about 😅 

It's not like I was suggesting to disable something for all modules or something 😉
