### ISSUE TITLE
Update Pinned or Linked field with current number of duplicates

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#57]
From the old Ruby Arisa project: https://github.com/mojira/arisa/issues/2

It would be great if Arisa could automatically set either the "Pinned" or "Linked" field to the number of duplicates of that ticket. Both of these fields are currently unused, but one of them (don't know which) has been used for that purpose before.

Arisa could slowly crawl through all the tickets on the tracker in order to update that value for older tickets, and also update that field whenever a new link is added.

**Comment by NeunEinser** [comment]
That's the same as #51, right?
Maybe @urielsalis was a bit quick with closing that one though 😅

**Comment by violine1101** [comment]
Yep, it's the same issue as 51, but I didn't see it since it was closed already.
