### ISSUE TITLE
Arisa detects seeds as transaction IDs

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#571]
## The Bug
Arisa detects any string of 17 numbers as a transaction ID. However, these are far more likely seeds.

## Example Ticket
https://bugs.mojang.com/browse/MC-217404

## Expected behavior
Don't detect those types of transaction IDs.

The current regexes are far too error-prone, although I don't really know how that could be changed easily.

**Comment by urielsalis** [comment]
https://github.com/mojira/arisa-kt/blob/master/src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt#L17

@CubeTheThird can we make that regex check that there are a mix of letters and numbers?

**Comment by SPGoding** [comment]
```regex
^(?=.*[A-Z])(?=.*[0-9])[A-Z0-9]{17}$
```
([SO](https://stackoverflow.com/questions/58792688/regex-for-a-combination-of-chars-and-digits-of-certain-length))

**Comment by Marcono1234** [comment]
> ```regexp
> ^(?=.*[A-Z])(?=.*[0-9])[A-Z0-9]{17}$
> ```
> 
> ([SO](https://stackoverflow.com/questions/58792688/regex-for-a-combination-of-chars-and-digits-of-certain-length))

Though without `^` (start of line) and `$` (end of line), otherwise we will likely get nearly no matches at all.

**Comment by urielsalis** [comment]
![image](https://user-images.githubusercontent.com/7349355/109520859-f4812500-7aac-11eb-98a6-9857acac61a8.png)
![image](https://user-images.githubusercontent.com/7349355/109520907-ff3bba00-7aac-11eb-8db5-5e0fa2c53d20.png)

note that it detects as a match even if the letter is not in the matched text or there is a space

**Comment by chandler05** [comment]
Modified regex to prevent ^
`(?<![^\s])(?=[^\s]*[A-Z])(?=[^\s]*[0-9])[A-Z0-9]{17}(?![^\s])`

**Comment by Marcono1234** [comment]
That should work, though it would not use `\b` (word boundary) anymore as separator, instead it would require `\s` (whitespace) (or start / end of line), but I guess that does not matter much.

The following should work as well and uses `\b`, but maybe using `\s` would actually be better to reduce false positives?
```regex
\b(?=[A-Z0-9]*[A-Z])(?=[A-Z0-9]*[0-9])[A-Z0-9]{17}\b
```
https://regex101.com/r/kPKMUp/1

**Comment by CubeTheThird** [comment]
Late to the party, but I might recommend this version instead:

`(?=[A-Z0-9]{0,16}[A-Z])(?=[A-Z0-9]{0,16}[0-9])[A-Z0-9]{17}`

It doesn't have to match word boundaries, but still enforces that the string must contain 1 digit and 1 caps character inside the next 17 characters. It's also a bit more efficient since it doesn't check for 0 or more characters, but instead limits the number of possibilities.
