### ISSUE TITLE
Resolve TRASHed tickets automatically

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#58]
https://github.com/mojira/arisa/blob/master/modules/trash.rb

**Comment by urielsalis** [comment]
Currently this is not possible with Jira REST API https://community.atlassian.com/t5/Jira-questions/Is-it-possible-to-programatically-move-issue-to-another-project/qaq-p/936099

**Comment by Pokechu22** [comment]
That seems to be about moving issues into the TRASH project; I assume this is about automatically resolving issues that have been moved into the TRASH project (e.g. as invalid) which seems perfectly doable.

**Comment by urielsalis** [comment]
Ah, misunderstood the issue 😅 

Working on it now!

**Comment by urielsalis** [comment]
!depends on #86
