### ISSUE TITLE
Some Issues affecting 1.16.5 are reprimanded as "Marked as an Unreleased Version"

### ISSUE THREAD

**Issue by Ethanator2009** [mojira/arisa-kt#589]
I was on Jira and reported how Arisa had reprimanded some reports incorrectly. I was told how one of those problems was slightly incorrect yet there was still one issue about how Arisa reprimanded some reports affecting version 1.16.5 as an "unreleased version". (The Jira issue is [WEB-3855])

[MC-212359]

Not displaying the message to those kind of reports
![Proof1](https://user-images.githubusercontent.com/77936667/110403908-e8b4d600-804b-11eb-9213-9eb52d36c1c0.png)
![Proof2](https://user-images.githubusercontent.com/77936667/110403924-eeaab700-804b-11eb-9349-498062be958b.png)

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/110404024-bb642a00-8043-11eb-8712-350383eb16b8.png)

The user marked `Future Version - 1.17+` as affected, which was a future version and was removed by the bot.
