### ISSUE TITLE
Rename 'ARISA_REMOVE_USER'

### ISSUE THREAD

**Issue by Greymagic27** [mojira/arisa-kt#590]
## The Problem
Currently this command is misleading as rather than removing a user, it instead restricts their comments.
## Possible Solution
A solution would be to change it to ARISA_RESTRICT_COMMENTS or similar.

https://github.com/mojira/arisa-kt/wiki/Commands#arisa_remove_user

**Comment by chandler05** [comment]
This also removes user attachments, so RESTRICT_COMMENTS wouldn't be correct either

**Comment by Greymagic27** [comment]
What about REMOVE_CONTENT

**Comment by chandler05** [comment]
REMOVE_USER_CONTENT?

**Comment by Greymagic27** [comment]
I was thinking ARISA_REMOVE_CONTENT [Username]

**Comment by chandler05** [comment]
Ok, I see that working.
