### ISSUE TITLE
isKeepARMessage not working properly

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#595]
## The Bug

The [`isKeepARMessage` method](https://github.com/mojira/arisa-kt/blob/90aa4c99291c379518f80b640f5c14ee732c6941/src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt#L81) checks if the comment contains the helper message key (`message`), instead of the actual message.

## Example Ticket

https://bugs.mojang.com/browse/MC-224188

**Comment by chandler05** [comment]
I knew just from reading the description that I was the one that implemented it that way 🤦‍♂️

I'll fix this later today
