### ISSUE TITLE
Arisa fails to revert a change to affected versions on a resolved report when only one version is affected and two versions are switched

### ISSUE THREAD

**Issue by dericksonmark** [mojira/arisa-kt#601]
## The Bug
When a resolved ticket has only one affected version, and the reporter switches the affected version for another version (in the same action), Arisa tries but fails to remove the new affected version. This is probably because it can't empty the field (it tries to).
## Example Ticket
MC-222695 (private), and https://bugs.mojang.com/browse/MC-224653 (public)
## Expected behavior
Arisa removes the new affected version and replaces it with the old one, or Arisa does nothing (no attempt to complete an action it can't complete)

**Comment by chandler05** [comment]
Arisa will just do nothing in this case.
