### ISSUE TITLE
Commands wiki documentation is outdated

### ISSUE THREAD

**Issue by Asteraoth** [mojira/arisa-kt#604]
## The problem
The [Commands](https://github.com/mojira/arisa-kt/wiki/Commands#arisa_remove_comments) page in the wiki documentation is outdated. The command ARISA_REMOVE_USER got its syntax changed to ARISA_REMOVE_CONTENT. Additionally, the command ARISA_NO_DUPLICATE_MESSAGE, along with its aliases, is missing.

**Comment by chandler05** [comment]
Fixed.
