### ISSUE TITLE
Revoke changes done to mojang_internal_x labels done by non-Mojang-staff

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#61]
Whenever a label matching`mojang_internal_[0-9]+` is either removed or added by someone who is not a Mojang employee, this action should be revoked by Arisa.

**Comment by Marcono1234** [comment]
Or maybe in general have some kind of permission config for certain labels?
For example we were asked to add a certain label for dispenser functionality, so in this case that label should possibly only be allowed to be set by volunteers and up?

**Comment by chandler05** [comment]
Maybe the labels could be turned into categories instead, so normal users couldn't change them?

**Comment by NeunEinser** [comment]
Mojang might have reasons to use labels here, you would have to ask them. It's not something we can control.

**Comment by urielsalis** [comment]
Those labels are no longer used

**Comment by Marcono1234** [comment]
> Those labels are no longer used

It looks like Henrik Kniberg is still using them now and then, e.g. on 20th of April 2021 [here](https://bugs.mojang.com/browse/MC-212113?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel#changehistory-2138539).
Though usage of it is pretty rare, and "safer" alternatives have been suggested internally, so having this module might not be worth it.
