### ISSUE TITLE
Replace comment links in description with the content of that comment

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#629]
## The Problem
It would be nice if Arisa could replace comment links with the actual comment content
## Possible Implementation
Format to make the module even more useful:

```
h3.Comment(link) by user(link) on ticket
{quote}
Comment content
{quote}
```

**Comment by misode** [comment]
This seems like a bad idea, it could cause problems if the user deletes or edits their comment, or if the comment is extremely long (for example code analysis).

**Comment by Marcono1234** [comment]
> for example code analysis

For code analyses it also happens that the commenter edits their comment to correct a mistake. In that case the comment included in the description would still contain the mistake, unless Arisa tried to update the description as well, but that probably becomes rather complex.

**Comment by violine1101** [comment]
I'd agree, this would probably just break more things than it'd solve.

**Comment by chandler05** [comment]
3 for 3 on not implementing this, so I'll close it.
