### ISSUE TITLE
Remove links that appear multiple times

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#68]
I noticed quite recently, when mass-linking some related tickets that the jira API allows for adding the same link with the same link type multiple times.
Arisa should remove a link that appears twice, if it is the same link type (relates to/ duplicates/ ...)

**Comment by urielsalis** [comment]
which one should be removed?

**Comment by NeunEinser** [comment]
All but one, if they are the same. Which one stays doesn't really matter.
