### ISSUE TITLE
There is no feedback while Arisa is catching up

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#687]
## The Bug
When arisa is down for a lot of time and its catching up, it processes all tickets at once so it can show no feedback for over an hour

## Expected behavior
We should catch up in steps(maybe 10 min increments?) so we can atleast see it do actions in tickets

**Comment by violine1101** [comment]
This will be fixed by #689 - although the feedback will be mostly debug messages, so only visible in the console.

**Comment by urielsalis** [comment]
Ideally we add that catching up is done in increments in that PR, to ease the load on the CPU and memory (and GC can catch up)
