### ISSUE TITLE
`FixedCommand` should reject versions older than affected versions

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#696]
## The Problem
(This has been brought up by @NeunEinser internally)

The issue is that game versions are pretty similar and it is easy to mistype them, e.g. writing `20w17a` instead of `21w17a` by accident. Since archived fixed versions cannot be removed again it is impossible to correct this mistake afterwards.

## Possible Solution
`FixedCommand` should reject versions which are older than the earliest affected version.
If for some reason the affected versions are incomplete, the user should manually add them using `AddVersionCommand` and afterwards set the fixed version.

Note that `AddVersionCommand` should probably not be adjusted, there might be cases where a report does not include the earliest version in which a bug occurred, so it might be desired to add an earlier affected version.

**Comment by Pokechu22** [comment]
IMO it would be useful to have a way to override this; *sometimes* an affected version can be added and then archived when the issue was actually fixed earlier on.  It's rare, but it's something that should be available.

**Comment by Marcono1234** [comment]
Yes, @chandler05, I think you misunderstood this issue. The proposed solution was:

> `FixedCommand` should reject versions which are older than the earliest affected version.

That would then still allow adding a fixed version, even when an erroneous newer affected version exists.

The implemented solution rejects the fixed version if it is older than _any_ (instead of _the earliest_) affected version.
In case this deviation from the suggested solution was made on purpose, it would be good to discuss this first.
