### ISSUE TITLE
Auto-redact JVM crash reports

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#704]
## The Problem
JVM crash reports contain privacy sensitive information that causes any bug report with one to be privated immediately.

## Possible Solution
Automate what I've done in https://bugs.mojang.com/browse/MC-229049:
* Parse `hs_err_pid` crashes
* Regex privacy sensitive parts and replace them with `<redacted>`
* Attach redacted crash log with name `redacted_hs_err_pidXXXX.log`
* Delete original crash log

**Comment by Marcono1234** [comment]
One issue with this is that it will be more difficult to tell afterwards who originally uploaded the attachment (you would have to check the History of the issue). Could be solvable by including the uploader name in the file name, but we have to sanitize it, and maybe also make sure to not accidentially expose the e-mail address of a user in case they entered it as Jira user name (happens now and then).
We also have to make sure this interacts well with `PrivacyModule` (or maybe implement it as part of that module?).

**Comment by violine1101** [comment]
> One issue with this is that it will be more difficult to tell afterwards who originally uploaded the attachment (you would have to check the History of the issue). Could be solvable by including the uploader name in the file name, but we have to sanitize it, and maybe also make sure to not accidentially expose the e-mail address of a user in case they entered it as Jira user name (happens now and then).

Perhaps Arisa could just leave a restricted(?) comment, similar to how it does when removing attachments with disallowed file extensions, with information about the reuploaded attachment.
