### ISSUE TITLE
Command to remove all labels on a report

### ISSUE THREAD

**Issue by dericksonmark** [mojira/arisa-kt#713]
## The Problem
This.
<img width="730" alt="Screen Shot 2021-07-10 at 3 55 49 PM" src="https://user-images.githubusercontent.com/68699877/125175456-48f28a80-e19a-11eb-94ea-c3fbf9a39388.png">
## Possible Solution
A command to remove all labels from a report could make clearing the field a lot easier in cases like this.
Relates to #381.

**Comment by violine1101** [comment]
Not sure if this is really necessary, you can just hold backspace while editing the labels and it'll delete everything. I haven't seen this happen more than once or twice during my entire time on the bug tracker, so not exactly a regular occurrence either.

**Comment by dericksonmark** [comment]
I agree. I haven't seen this happen anywhere else since then. I'll close the issue.
