### ISSUE TITLE
Future version comment still says the report was resolved as awaiting response

### ISSUE THREAD

**Issue by Greymagic27** [mojira/arisa-kt#726]
## The Bug
#725 changed the future version module by making it resolve reports as invalid rather than awaiting response, however the comment still contains the message 'This issue is being temporarily closed as Awaiting Response. Once the requested information has been delivered, the report will be reopened automatically.'
## Example Ticket
https://bugs.mojang.com/browse/MC-232220
## Expected behavior
This message should be changed to reflect the new resolution

**Comment by chandler05** [comment]
This a helper messages issue, please report it there.

**Comment by Marcono1234** [comment]
Note for the future: You can also transfer issues to different repositories:
![GitHub screenshot](https://user-images.githubusercontent.com/11685886/126051891-61b0d056-9fc2-4f23-a868-94e6b8f3b749.png)
