### ISSUE TITLE
RevokeConfirmation module revokes confirmation set by former volunteers

### ISSUE THREAD

**Issue by NeunEinser** [mojira/arisa-kt#75]
Currently, the module will revoke any confirmation which was last set by someone who is not in group helper, global-moderators or staff.
This has the unwanted effect that it will also revoke tickets confirmed by people who used to, but no longer are volunteers.

The easiest way to fix this would probably be to assume a change was made by a volunteer for old entries.

**Comment by urielsalis** [comment]
A filter for only confirmations that happened in the last day similar to how its done in the HideImpostors module should work
