### ISSUE TITLE
`PurgeAttachmentCommand`'s range arguments don't work

### ISSUE THREAD

**Issue by Pokechu22** [mojira/arisa-kt#759]
## The Bug

The username argument for the purge attachment command is a greedy string, so the range arguments afterwards never get parsed.  For instance, `$ARISA_PURGE_ATTACHMENT Username 468330 468405` tries to purge all attachments from a user with the name `Username 468330 468405`, instead of trying to purge attachments from a user with the name `Username` where the attachment ID is between 468330 and 468405 (inclusive?).

https://github.com/mojira/arisa-kt/blob/b4be4c306d88ae7ede5208d68eb0f2fea40baca5/src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt#L208

The test did not pick up on this, because the test directly runs the command instead of going through the parsing step.

## Example Ticket
https://bugs.mojang.com/browse/MC-247000 (I worked around this issue by purging all attachments and then re-uploading the relevant ones)

## Expected behavior
I'm not sure how to resolve this ambiguity while still having the range arguments be optional and the username argument be mandatory.

**Comment by SPGoding** [comment]
We could either change to use a phrase string parser for username (which requires quotes for special characters), or try some syntax like `$ARISA_PURGE_ATTACHMENT [from <min> [to <max>]] by <username>` :thinking:
