### ISSUE TITLE
Enable CodeQL code scanning

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#811]
GitHub's CodeQL supports Kotlin since a while now (even Kotlin version 1.9.0 apparently, see [changelog](https://github.com/github/codeql/blob/codeql-cli/v2.14.0/java/ql/lib/CHANGELOG.md#063)), and there is also a [default setup](https://github.blog/changelog/2023-06-29-code-scanning-default-setup-is-now-available-for-all-codeql-supported-languages-excluding-swift/) which allows enabling CodeQL from the GitHub UI (though even enabling it manually using a config file is also not complicated).

So maybe we could consider enabling it for this repository?
(if you want I can do that)

@urielsalis, @violine1101 what are your thoughts?

**Comment by urielsalis** [comment]
Sounds good! IIRC CodeQL uses detekt behind the scenes (same as we do) so we shouldnt get too many things

**Comment by violine1101** [comment]
Generally seems like a good idea - however, the `mojira-discord-bot` repo used to use CodeQL, but I disabled it there recently: https://github.com/mojira/mojira-discord-bot/commit/034c6f8c4084975ad1d7d7d162c953541efc9e9c

It caused issues with the workflow getting stuck if the pull request comes from an external repository. I didn't find a way to fix this issue, and I also didn't CodeQL to be particularly useful for `mojira-discord-bot`, so I just removed that workflow.

I don't think we'll get many external PRs on this project though, so this wouldn't be a blocker. I just am not sure if there's a point in enabling CodeQL here if detekt runs with our current CI anyways.

**Comment by Marcono1234** [comment]
> IIRC CodeQL uses detekt behind the scenes

No CodeQL is a dedicated code querying language unrelated to Detekt. Here is a list of the default queries they support for Java and Kotlin: https://codeql.github.com/codeql-query-help/java/
(Java and Kotlin share the same CodeQL library code, which is why this page says "Java"; but I think most or all of the queries should apply to Kotlin as well.)

I have enabled it now, but we can definitely disable it again if it blocks something; you can find it under "Code security and analysis" in the repository settings:
![Repository settings screenshot](https://github.com/mojira/arisa-kt/assets/11685886/289ce578-8f9b-4909-94dc-546f21b599b6)

For now I have enabled the "Default" query suite (which does not contain all the queries listed above). I think it mostly contains security related queries with low false-positive rates; but I also assume we won't get much or any alerts, but let's see. Looks like it did not find anything for the current state of `master`.
