### ISSUE TITLE
Switch jira library

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#84]
Should be relatively easy, as we should try to move all jira stuff to Jira.kt

**Comment by urielsalis** [comment]
The official library is https://bitbucket.org/atlassian/jira-rest-java-client/src/master/

**Comment by Marcono1234** [comment]
Is "Jira.kt" an existing library? If so could you provide a link please? I am currently unable to find it.

**Comment by SPGoding** [comment]
The official library doesn't seem to support deleting attachments.

Are there any reasons why we need switch to another Jira library?

**Comment by urielsalis** [comment]
It was due to limitations in the current one, which we seem to have gotten rid of anyway

**Comment by urielsalis** [comment]
I would say close this for now, reopen if we need it
